### ISSUE TITLE
IJulia bails on typing "00" in jupyter lab 2.1

### ISSUE THREAD

**Issue by pfarndt** [JuliaLang/IJulia.jl#929] opened 2020-05-27 11:51 UTC
IJulia (julia v1.4.2 in jupyter lab version 2.1) gets unresponsive if one types `00` (literally two zeros) in a code block. Only the first `0` will appear and the code block stalls. Alternatively, write `max(1, 200)` and try to remove the `2`.

I think the problem has something to do with syntax coloring. In jupyter lab 1.2 all is fine - the first of the zeros will appear in red indicating that this is not a valid expression.

**Comment by stevengj** [comment] 2020-05-27 12:18
Seems to be a duplicate of codemirror/CodeMirror#6288

**Closed** 2020-05-27 12:19 UTC
