### ISSUE TITLE
Semicolon doesn't work when cell ends with a comment line

### ISSUE THREAD

**Issue by jonalm** [JuliaLang/IJulia.jl#456] opened 2016-09-05 20:02 UTC
When endig a cell with a comment like this:

```julia
x = collect(1:1000);
# comment here
```

the semicolon does not prevent displaying `x`, using IJulia 1.2.0, Julia 0.5.0-rc3 and jupyter 4.1.0. This is rather unfortunate when working with large arrays. See #455.

**Comment by stevengj** [comment] 2016-09-05 20:45
Duplicate of #109.  Doesn't seem worth fixing, as doing this right requires a significant chunk of the Julia parser, as discussed in #109.

**Closed by stevengj** 2016-09-05 20:45 UTC
