### ISSUE TITLE
Kernel does not start and keep restarting

### ISSUE THREAD

**Issue by gdmsl** [JuliaLang/IJulia.jl#328] opened 2015-07-06 16:17 UTC
Hi,
I updated to Julia 0.3.10 on archlinux but ijulia is not starting.
I'm doing `ipython notebook` from commandline with `ipython 3.2.0`.

```
[I 18:01:04.352 NotebookApp] Creating new notebook in /Simulations/chain_excitation
[I 18:01:06.893 NotebookApp] Kernel started: 01574c95-5f38-4a48-ae76-aec2e91b7407
[W 18:01:06.909 NotebookApp] 404 GET /kernelspecs/julia-0.3/logo-64x64.png (::1) 13.79ms referer=http://localhost:8888/notebooks/Simulations/chain_excitation/Untitled1.ipynb?kernel_name=julia-0.3
[I 18:01:15.894 NotebookApp] KernelRestarter: restarting kernel (1/5)
[W 18:01:16.976 NotebookApp] Timeout waiting for kernel_info reply from 01574c95-5f38-4a48-ae76-aec2e91b7407
```
Kernel keeps restarting (always with 1/5). I have also deleted both .ipython and .julia dirs and installed all packages again; nothing is changed.
I also tried to use both IJulia, ZMQ and Nettle from master with `Pkg.checkout(pkg)`  for all the packages and then `Pkg.build("IJulia")`; got no errors while building but the problem persists.

Thanks for helping.

**Comment by stevengj** [comment] 2015-07-06 17:55
See the [debugging instructions](https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems) to see if you can get a more detailed error message.

**Comment by gdmsl** [comment] 2015-07-06 18:45
I am getting these errors with debugging options true:
```
[I 20:37:55.813 NotebookApp] Creating new notebook in /Simulations/chain_excitation
[I 20:37:55.818 NotebookApp] Writing notebook-signing key to /home/gdmsl/.ipython/profile_default/security/notebook_secret
[I 20:37:58.171 NotebookApp] Kernel started: 3583df9e-f7ca-412a-8788-80a6206514eb
[W 20:37:58.196 NotebookApp] 404 GET /kernelspecs/julia-0.3/logo-64x64.png (::1) 20.74ms referer=http://localhost:8888/notebooks/Simulations/chain_excitation/Untitled.ipynb?kernel_name=julia-0.3
PROFILE = ["key"=>"0c073472-fc64-45d0-b239-8eb0963cda10","transport"=>"tcp","signature_scheme"=>"hmac-sha256","shell_port"=>35134,"hb_port"=>42693,"control_port"=>50595,"ip"=>"127.0.0.1","stdin_port"=>48303,"iopub_port"=>55271]
SENDING IPython Msg [ idents status ] {
  header = ["msg_id"=>"0e39d26d-829e-466b-ae03-0a60a5d70fc8","msg_type"=>"status","username"=>"jlkernel","session"=>"????"],
  metadata = Dict{String,Any}(),
  content = ["execution_state"=>"starting"]
}

signal (11): Segmentation fault
unknown function (ip: 1706934514)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
setindex! at dict.jl:559
Message at /home/gdmsl/.julia/v0.3/ZMQ/src/ZMQ.jl:415
send_ipython at /home/gdmsl/.julia/v0.3/IJulia/src/msg.jl:50
jlcall_send_ipython_20621 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
send_status at /home/gdmsl/.julia/v0.3/IJulia/src/msg.jl:108
init at /home/gdmsl/.julia/v0.3/IJulia/src/IJulia.jl:107
jlcall_init_20531 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 1707231224)
unknown function (ip: 1707227737)
unknown function (ip: 1707296445)
unknown function (ip: 1707299136)
jl_load at /usr/bin/../lib/julia/libjulia.so (unknown line)
include at /usr/bin/../lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
include_from_node1 at loading.jl:128
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
process_options at /usr/bin/../lib/julia/sys.so (unknown line)
_start at /usr/bin/../lib/julia/sys.so (unknown line)
jlcall__start_17441 at /usr/bin/../lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 4200709)
julia_trampoline at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 4199613)
__libc_start_main at /usr/bin/../lib/libc.so.6 (unknown line)
unknown function (ip: 4199673)
unknown function (ip: 0)
[I 20:38:07.172 NotebookApp] KernelRestarter: restarting kernel (1/5)
[W 20:38:08.348 NotebookApp] Timeout waiting for kernel_info reply from 3583df9e-f7ca-412a-8788-80a6206514eb
```

These messages repeats each time kernel tries to restart.

**Comment by swadey** [comment] 2015-07-07 01:15
i'm seeing the same issue on macos 10.10 with anaconda ipython 3.2.0

**Comment by stevengj** [comment] 2015-07-07 14:43
Sounds like a duplicate of JuliaLang/ZMQ.jl#83 ... are you using zeromq 4.1?

**Comment by gdmsl** [comment] 2015-07-07 15:52
Yes. I'm using ZMQ `4.1.2-3` from the official Archlinux repositories.

**Comment by stevengj** [comment] 2015-07-07 17:17
Closing as a duplicate of that issue, then.

**Closed by stevengj** 2015-07-07 17:17 UTC
