### ISSUE TITLE
Mac OSX installation problem

### ISSUE THREAD

**Issue by bwanab** [JuliaLang/IJulia.jl#770] opened 2018-10-31 01:33 UTC
When I do Pkg.build("IJulia") I get the following error:

│ ERROR: did not recognize option 'HD/Users/bill/.julia/conda/3', please try -h
│ [ Info: Installing Jupyter via the Conda package.
│ [ Info: Downloading miniconda installer ...
│ [ Info: Installing miniconda ...
│ ERROR: LoadError: failed process: Process(`'/Volumes/Macintosh HD/Users/bill/.julia/conda/3/installer.sh' -b -f -p '/Volumes/Macintosh HD/Users/bill/.julia/conda/3'`, ProcessExited(1)) [1]

It seems clear by the error message that it has trouble with the fact that the volume name Macintosh HD has a space in it. The suggestion to use -h is problematic since I have no idea where the -h would go in the command Pkg.build("IJulia"). Any ideas?

**Comment by stevengj** [comment] 2018-11-05 21:04
Ouch, this seems like a bug in Anaconda's `installer.sh` script.  (Mishandling paths with spaces is a perennial problem with shell scripts.)

(Conda.jl [is passing](https://github.com/JuliaPy/Conda.jl/blob/1a5d1d64504652104b3de476aa24e27d16f584a5/src/Conda.jl#L165) the path correctly as a single argument, because Julia executes programs directly with `fork` rather than via the shell, so I think this not "our" fault.)

(The suggestion `-h` is irrelevant, I think—it is just suggesting that you consult the help.)

**Comment by stevengj** [comment] 2018-11-05 21:09
The right thing to do is to first reproduce the problem without using Julia, and then file a bug with Anaconda.

Steps to reproduce:

1. Download the Miniconda installer: https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh

2. Run it in the Terminal: 
```sh
sh Miniconda3-latest-MacOSX-x86_64.sh -b -f -p /some/path/with/space
```

**Comment by stevengj** [comment] 2018-11-05 21:11
Actually, it seems it has already been reported: ContinuumIO/anaconda-issues#716

**Comment by stevengj** [comment] 2018-11-05 21:48
Closing as a duplicate of that anaconda issue.

In the meantime, the workaround is not to use a path with spaces.    (On my MacOS X box, the user home directory is simply `/Users/username` … under what circumstances does the home directory name include the name of the drive?)

**Closed by stevengj** 2018-11-05 21:48 UTC

**Comment by bwanab** [comment] 2018-11-06 01:17
Thanks for looking into this. I was able to work around it using the
instructions on the IJulia github page by setting ENV["JUPYTER"]=<my local
ijulia> since I'd previously installed anaconda. It's hard for me to
believe this is an issue (for them not you) when all Macs are set up like
this by default. Not a good default, but still....
