### ISSUE TITLE
Error with MbedTLS

### ISSUE THREAD

**Issue by JulienPascal** [JuliaLang/IJulia.jl#685] opened 2018-07-18 08:34 UTC
Hi,

I had already IJulia installed, but the kernel would randomly die. So I tried a "Pkg.update()", followed by "Pkg.build("IJulia")". Now I have a new error message, related to MbedTLS, which I am unable to solve:

```julia
julia> ENV["JUPYTER"] = "/usr/local/bin/jupyter-notebook"; Pkg.build("IJulia")
INFO: Building Conda
INFO: Building MbedTLS
===============================[ ERROR: MbedTLS ]===============================

LoadError: MethodError: no method matching BinaryProvider.Linux(::Symbol, ::Symbol, ::Symbol)
Closest candidates are:
  BinaryProvider.Linux(::Symbol, ::Symbol) at /home/julien/.julia/v0.6/BinaryProvider/src/PlatformNames.jl:11
  BinaryProvider.Linux(::Symbol) at /home/julien/.julia/v0.6/BinaryProvider/src/PlatformNames.jl:11
while loading /home/julien/.julia/v0.6/MbedTLS/deps/build.jl, in expression starting on line 24

================================================================================
INFO: Building ZMQ
=================================[ ERROR: ZMQ ]=================================

LoadError: MethodError: no method matching BinaryProvider.Linux(::Symbol, ::Symbol, ::Symbol)
Closest candidates are:
  BinaryProvider.Linux(::Symbol, ::Symbol) at /home/julien/.julia/v0.6/BinaryProvider/src/PlatformNames.jl:11
  BinaryProvider.Linux(::Symbol) at /home/julien/.julia/v0.6/BinaryProvider/src/PlatformNames.jl:11
while loading /home/julien/.julia/v0.6/ZMQ/deps/build.jl, in expression starting on line 14

================================================================================
INFO: Building IJulia
INFO: Found Jupyter version 5.0.0: /usr/local/bin/jupyter-notebook
INFO: Installing Julia kernelspec julia-0.6
The Jupyter HTML Notebook.

This launches a Tornado based HTML Notebook Server that serves up an
HTML5/Javascript Notebook client.

Subcommands
-----------

Subcommands are launched as `jupyter-notebook cmd [args]`. For information on
using subcommand 'cmd', do: `jupyter-notebook cmd -h`.

password
    Set a password for the notebook server.
list
    List currently running notebook servers.

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--no-browser
    Don't open the notebook in a browser after startup.
--allow-root
    Allow the notebook to be run from root user.
--no-mathjax
    Disable MathJax
    
    MathJax is the javascript library Jupyter uses to render math/LaTeX. It is
    very large, so you may want to disable it if you have a slow internet
    connection, or for offline use of the notebook.
    
    When disabled, equations etc. will appear as their untransformed TeX source.
-y
    Answer yes to any questions instead of prompting.
--debug
    set log level to logging.DEBUG (maximize logging output)
--generate-config
    generate default config file
--script
    DEPRECATED, IGNORED
--pylab
    DISABLED: use %pylab or %matplotlib in the notebook to enable matplotlib.
--no-script
    DEPRECATED, IGNORED
--transport=<CaselessStrEnum> (KernelManager.transport)
    Default: 'tcp'
    Choices: ['tcp', 'ipc']
--client-ca=<Unicode> (NotebookApp.client_ca)
    Default: ''
    The full path to a certificate authority certificate for SSL/TLS client
    authentication.
--ip=<Unicode> (NotebookApp.ip)
    Default: 'localhost'
    The IP address the notebook server will listen on.
--log-level=<Enum> (Application.log_level)
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.
--keyfile=<Unicode> (NotebookApp.keyfile)
    Default: ''
    The full path to a private key file for usage with SSL/TLS.
--port=<Int> (NotebookApp.port)
    Default: 8888
    The port the notebook server will listen on.
--certfile=<Unicode> (NotebookApp.certfile)
    Default: ''
    The full path to an SSL/TLS certificate file.
--browser=<Unicode> (NotebookApp.browser)
    Default: ''
    Specify what command to use to invoke a web browser when opening the
    notebook. If not specified, the default browser will be determined by the
    `webbrowser` standard library module, which allows setting of the BROWSER
    environment variable to override it.
--notebook-dir=<Unicode> (NotebookApp.notebook_dir)
    Default: ''
    The directory to use for notebooks and kernels.
--config=<Unicode> (JupyterApp.config_file)
    Default: ''
    Full path of a config file.
--port-retries=<Int> (NotebookApp.port_retries)
    Default: 50
    The number of additional ports to try if the specified port is not
    available.
--pylab=<Unicode> (NotebookApp.pylab)
    Default: 'disabled'
    DISABLED: use %pylab or %matplotlib in the notebook to enable matplotlib.

To see all available configurables, use `--help-all`

Examples
--------

    jupyter notebook                       # start the notebook
    jupyter notebook --certfile=mycert.pem # use SSL/TLS certificate
    jupyter notebook password              # enter a password to protect the server

[C 10:28:42.908 NotebookApp] Bad config encountered during initialization:
[C 10:28:42.908 NotebookApp] Unrecognized flag: '--replace'
===============================[ ERROR: IJulia ]================================

LoadError: could not spawn `/usr/local/bin/jupyter-notebook-kernelspec install --replace --user /tmp/julia-0.6`: no such file or directory (ENOENT)
while loading /home/julien/.julia/v0.6/IJulia/deps/build.jl, in expression starting on line 117

================================================================================
ERROR: UndefVarError: BinaryProvider not defined
Stacktrace:
 [1] deserialize_module(::SerializationState{IOStream}) at ./serialize.jl:757
 [2] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:698
 [3] deserialize(::SerializationState{IOStream}) at ./serialize.jl:637
 [4] deserialize_datatype(::SerializationState{IOStream}, ::Bool) at ./serialize.jl:972
 [5] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:677
 [6] deserialize(::SerializationState{IOStream}, ::DataType) at ./serialize.jl:1079
 [7] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:690
 [8] deserialize(::SerializationState{IOStream}, ::DataType) at ./serialize.jl:1079
 [9] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:690
 [10] (::Base.Pkg.Entry.##54#55{Dict{Any,Any}})(::IOStream) at ./pkg/entry.jl:639
 [11] open(::Base.Pkg.Entry.##54#55{Dict{Any,Any}}, ::String, ::String) at ./iostream.jl:152
 [12] build!(::Array{String,1}, ::Dict{Any,Any}, ::Set{Any}) at ./pkg/entry.jl:636
 [13] build(::Array{String,1}) at ./pkg/entry.jl:650
 [14] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#build,Tuple{Array{String,1}}})() at ./pkg/dir.jl:36
 [15] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#build,Tuple{Array{String,1}}}, ::String) at ./file.jl:70
 [16] #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{String,1}, ::Vararg{Array{String,1},N} where N) at ./pkg/dir.jl:36
 [17] build(::String, ::Vararg{String,N} where N) at ./pkg/pkg.jl:254
```

If I try to install IJulia  using Conda, I get a similar error message:
```julia
ENV["JUPYTER"] = ""; Pkg.build("IJulia")
INFO: Building Conda
INFO: Building MbedTLS
===============================[ ERROR: MbedTLS ]===============================

LoadError: MethodError: no method matching BinaryProvider.Linux(::Symbol, ::Symbol, ::Symbol)
Closest candidates are:
  BinaryProvider.Linux(::Symbol, ::Symbol) at /home/julien/.julia/v0.6/BinaryProvider/src/PlatformNames.jl:11
  BinaryProvider.Linux(::Symbol) at /home/julien/.julia/v0.6/BinaryProvider/src/PlatformNames.jl:11
while loading /home/julien/.julia/v0.6/MbedTLS/deps/build.jl, in expression starting on line 24

================================================================================
INFO: Building ZMQ
=================================[ ERROR: ZMQ ]=================================

LoadError: MethodError: no method matching BinaryProvider.Linux(::Symbol, ::Symbol, ::Symbol)
Closest candidates are:
  BinaryProvider.Linux(::Symbol, ::Symbol) at /home/julien/.julia/v0.6/BinaryProvider/src/PlatformNames.jl:11
  BinaryProvider.Linux(::Symbol) at /home/julien/.julia/v0.6/BinaryProvider/src/PlatformNames.jl:11
while loading /home/julien/.julia/v0.6/ZMQ/deps/build.jl, in expression starting on line 14

================================================================================
INFO: Building IJulia
INFO: Installing Jupyter via the Conda package.
Solving environment: done

# All requested packages already installed.

INFO: Found Jupyter version 4.4.0: /home/julien/.julia/v0.6/Conda/deps/usr/bin/jupyter
INFO: Installing Julia kernelspec julia-0.6
[InstallKernelSpec] Removing existing kernelspec in /home/julien/.local/share/jupyter/kernels/julia-0.6
[InstallKernelSpec] Installed kernelspec julia-0.6 in /home/julien/.local/share/jupyter/kernels/julia-0.6
ERROR: UndefVarError: BinaryProvider not defined
Stacktrace:
 [1] deserialize_module(::SerializationState{IOStream}) at ./serialize.jl:757
 [2] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:698
 [3] deserialize(::SerializationState{IOStream}) at ./serialize.jl:637
 [4] deserialize_datatype(::SerializationState{IOStream}, ::Bool) at ./serialize.jl:972
 [5] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:677
 [6] deserialize(::SerializationState{IOStream}, ::DataType) at ./serialize.jl:1079
 [7] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:690
 [8] deserialize(::SerializationState{IOStream}, ::DataType) at ./serialize.jl:1079
 [9] handle_deserialize(::SerializationState{IOStream}, ::Int32) at ./serialize.jl:690
 [10] (::Base.Pkg.Entry.##54#55{Dict{Any,Any}})(::IOStream) at ./pkg/entry.jl:639
 [11] open(::Base.Pkg.Entry.##54#55{Dict{Any,Any}}, ::String, ::String) at ./iostream.jl:152
 [12] build!(::Array{String,1}, ::Dict{Any,Any}, ::Set{Any}) at ./pkg/entry.jl:636
 [13] build(::Array{String,1}) at ./pkg/entry.jl:650
 [14] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#build,Tuple{Array{String,1}}})() at ./pkg/dir.jl:36
 [15] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#build,Tuple{Array{String,1}}}, ::String) at ./file.jl:70
 [16] #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{String,1}, ::Vararg{Array{String,1},N} where N) at ./pkg/dir.jl:36
 [17] build(::String, ::Vararg{String,N} where N) at ./pkg/pkg.jl:254

```

I am using julia v0.6.1 on Ubuntu LTS 16.04
```julia 
julia> versioninfo()
Julia Version 0.6.1
Commit 0d7248e2ff (2017-10-24 22:15 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

Any suggestion on how to solve this issue?
Thanks.

**Comment by stevengj** [comment] 2018-07-18 11:07
Duplicate of JuliaWeb/MbedTLS.jl#153

**Closed by stevengj** 2018-07-18 11:07 UTC
