### ISSUE TITLE
code_warntype not highlighting warnings

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/IJulia.jl#310] opened 2015-05-19 18:54 UTC
Consider
```julia
f()=rand()>.5 ? 1 : 0.0
@code_warntype f()
```

In the terminal, the problematic ``Union`` type inferences are highlighted in red, but not in IJulia. Kinda defeats the point of the macro.

**Comment by stevengj** [comment] 2015-05-19 19:13
Could it be updated to output a `MarkdownText` object or similar, so that it could be formatted correctly?  Terminal formatting codes are not going to work here.

**Comment by stevengj** [comment] 2015-05-19 19:16
I don't think there is anything that can be done on the IJulia side.  The problem is that `code_warntype` uses `println` and terminal formatting.  This needs to be fixed on the Julia side: it needs to output an object that encodes the formatting.

**Closed by stevengj** 2015-05-19 19:16 UTC
