### ISSUE TITLE
Getting IJulia to work on Julia 0.4

### ISSUE THREAD

**Issue by tlycken** [JuliaLang/IJulia.jl#349] opened 2015-08-31 11:39 UTC
I'm interested in trying to get IJulia working on 0.4, but it doesn't seem to out-of-the-box. I've changed the verbosity to `verbose = true` in `IJulia.jl`, and I'm starting the notebook from within Julia to make sure I'm using the right versions of everything.

I get to the Jupyter dashboard OK, but when I start an IJulia Notebook I get the following message repeated over and over again in the console

```
PROFILE = Dict{AbstractString,Any}("key"=>"9209a55b-3fd2-429c-8115-39b95c4bf772","transport"=>"tcp","signature_scheme"=>"hmac-sha256","shell_port"=>42627,"hb_port"=>42631,"control_port"=>42630,"ip"=>"127.0.0.1","stdin_port"=>42629,"iopub_port"=>42628)
[I 13:37:25.750 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel dd15f9fa-e810-461f-9457-5f0971ad7341 restarted
```

and the message `The kernel appears to have died. It will restart automatically.` in the browser interface.

I'll gladly help troubleshooting this to make it work, but I know very little of the internals and so will probably not be able to fix this myself.

Thanks in advance for any help!

**Comment by yuyichao** [comment] 2015-08-31 11:47
Are you using the master of the related packages?

**Comment by tlycken** [comment] 2015-08-31 12:06
@yuyichao: Thanks for the tip - I had forgotten to do that. I now checked out `ZMQ` and `IJulia` and rebuilt both. Unfortunately, I get the same results.

**Comment by stevengj** [comment] 2015-09-14 20:27
I can't reproduce... there have been some updates to IJulia recently, maybe try again?

**Comment by tlycken** [comment] 2015-09-15 06:50
On Julia 0.4.0-rc1, after `Pkg.checkout("IJulia")` and `Pkg.build("IJulia")` (and a restart of the Julia shell) I now get the following results:

```jl
julia> using IJulia; notebook()
[I 08:47:22.993 NotebookApp] Using existing profile dir: 'C:\\Users\\Tomas Lycken\\.ipython\\profile_default'
[I 08:47:22.998 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 08:47:23.038 NotebookApp] Serving notebooks from local directory: C:\Users\Tomas Lycken\AppData\Local\Julia-0.4.0-rc1

[I 08:47:23.038 NotebookApp] 0 active kernels
[I 08:47:23.038 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 08:47:23.038 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 08:47:29.604 NotebookApp] Creating new notebook in
[I 08:47:30.381 NotebookApp] Kernel started: 1e7e405c-35f2-4a5b-981a-5ee9c227e560
[W 08:47:30.389 NotebookApp] 404 GET /kernelspecs/julia-0.4/logo-64x64.png (::1) 6.00ms referer=http://localhost:8888/no
tebooks/Untitled1.ipynb?kernel_name=julia-0.4
[I 08:47:39.393 NotebookApp] KernelRestarter: restarting kernel (1/5)
[W 08:47:40.443 NotebookApp] Timeout waiting for kernel_info reply from 1e7e405c-35f2-4a5b-981a-5ee9c227e560
[I 08:47:48.394 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 1e7e405c-35f2-4a5b-981a-5ee9c227e560 restarted
```

The last two lines are repeated indefinitely, with a new pair written out every few seconds.

I'll update a few other packages as well and try again.

**Comment by stevengj** [comment] 2015-09-15 17:51
@tlycken, does just running `ipython notebook` (or `jupyter notebook`) on the Windows command-line work?

**Comment by tlycken** [comment] 2015-09-17 06:48
@stevengj Nope, that gives the same error (both from `cmd.exe` and PowerShell).

I doubt that this is strictly an IPython issue though, since it's only the Julia profiles that show this behavior; notebooks in Python work fine.

**Comment by stevengj** [comment] 2015-09-17 19:43
@minrk, it mentions a timeout being exceeded; could it fail if IJulia takes too much time to load on someone's machine?   Is there a simple way to increase the timeout?

**Comment by minrk** [comment] 2015-09-18 08:35
If it's restarting the kernel, that means it has tried to start and exited twice already. I'm guessing it's no starting at all.

**Comment by stevengj** [comment] 2015-09-18 15:13
@tlycken, see the debugging info (https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems) to see if you can get more output.

So far, I can't reproduce; it works fine for me on both Mac and Windows machines.

**Comment by tlycken** [comment] 2015-09-18 15:19
@stevengj Yeah, this might very well be a configuration problem more than anything else.

Here's the only extra output I get with `verbose = true` (I've added some whitespace for legibility):

```
PROFILE = Dict{AbstractString,Any}(
    "key"=>"a5be6636-4e67-4071-a9ec-998e7d0ecb3c",
    "transport"=>"tcp",
    "signature_scheme"=>"hmac-sha256",
    "shell_port"=>7387,
    "hb_port"=>7391,
    "ip"=>"127.0.0.1",
    "control_port"=>7390,
    "stdin_port"=>7389,
    "iopub_port"=>7388
)
```

**Comment by tlycken** [comment] 2015-10-22 21:46
After a wild goose-chase on upgrades of all sorts, I now have the following verbose output:

```
PROFILE = Dict{AbstractString,Any}(
    "key"=>"7036a504-4085-46ce-8c5d-6675693f9024",
    "transport"=>"tcp",
     "signature_scheme"=>
"hmac-sha256",
    "ip"=>"127.0.0.1",
    "hb_port"=>52390,
    "control_port"=>52389,
    "shell_port"=>52386,
    "stdin_port"=>52388,
    "iopub_port"=>52387
)
rt"=>52387)
```

and the following versions of things:

```
julia> versioninfo()
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.status()
6 required packages:
 - IJulia                        1.0.4              b161ef72 (dirty)
# ...
50 additional packages:
 - BinDeps                       0.3.18
 - Compat                        0.7.7
 - JSON                          0.5.0
 - Nettle                        0.2.0
 - SHA                           0.1.2
 - URIParser                     0.1.1
 - WinRPM                        0.1.13
 - ZMQ                           0.3.0
# ...
```

I got here by uninstalling all IJulia-related packages with `Pkg.rm`, then doing `conda upgrade --prefix=<path to conda> conda` as well as `conda install jupyter` before re-adding IJulia. Still the same timeout error.

**Comment by stevengj** [comment] 2015-10-22 22:44
Could it be related to #374, which was fixed by a `pyzmq` update?

**Comment by stevengj** [comment] 2017-02-04 03:19
I think this can be closed...

**Closed by stevengj** 2017-02-04 03:19 UTC
