### ISSUE TITLE
Precompiling packages in IJulia results in world age error

### ISSUE THREAD

**Issue by j605** [JuliaLang/IJulia.jl#677] opened 2018-07-10 03:26 UTC
This happens when I try to load `VegaLite` in jupyterlab.
```julia
MethodError: no method matching pipe_writer(::IJulia.IJuliaStdio{Base.PipeEndpoint})
The applicable method may be too new: running in world age 27505, while current world is 27510.
Closest candidates are:
  pipe_writer(::IJulia.IJuliaStdio) at /home/jagan/.julia/packages/IJulia/Nnq2/src/stdio.jl:15 (method too new to be called from this world context.)
  pipe_writer(!Matched::Base.ProcessChain) at process.jl:344
  pipe_writer(!Matched::Base.Process) at process.jl:332
  ...

Stacktrace:
 [1] unsafe_write(::IJulia.IJuliaStdio{Base.PipeEndpoint}, ::Ptr{UInt8}, ::UInt64) at ./io.jl:225
 [2] unsafe_write(::IJulia.IJuliaStdio{Base.PipeEndpoint}, ::Ptr{UInt8}, ::Int64) at ./io.jl:510
 [3] write(::IJulia.IJuliaStdio{Base.PipeEndpoint}, ::Array{UInt8,1}) at ./gcutils.jl:87
 [4] #handle_message#2(::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Base.CoreLogging.SimpleLogger, ::Base.CoreLogging.LogLevel, ::String, ::Module, ::Symbol, ::Symbol, ::String, ::Int64) at ./logging.jl:534
```
`julia` and `IJulia` are from git master.

**Comment by drewrobson** [comment] 2018-07-10 21:09
It's not just `VegaLite`. I'm seeing this on master too, `using` any package.

**Comment by fredrikekre** [comment] 2018-07-10 21:10
How do you trigger it?

**Comment by drewrobson** [comment] 2018-07-10 21:16
I compiled julia master (`25f91ab3068b92ef28ac462b545908c2d4687c83`) with gcc 7.3 on Ubuntu 16.04, then added `IJulia#master`. I also tried the IJulia nightly branch and saw the same thing.

**Comment by fredrikekre** [comment] 2018-07-10 21:38
Ok, thanks. I can reproduce too. This happens when precompiling the package. If you e.g. `using HDF5` outside the notebook, and then `using HDF5` inside it works for me.

**Comment by fredrikekre** [comment] 2018-07-10 22:02
Filed https://github.com/JuliaLang/julia/issues/28042 but perhaps worth trying to fix it here if there is no easy fix in Base.

**Comment by Nosferican** [comment] 2018-07-19 21:18
What's the status here? Should we wait for a new release of IJulia or use nightly?

**Comment by fredrikekre** [comment] 2018-07-19 21:32
Neither; we need a fix for JuliaLang/julia#28042

**Comment by Nosferican** [comment] 2018-07-19 21:34
So use any nightly after the one that closes that issue. Will track it, thanks.

**Comment by fredrikekre** [comment] 2018-07-26 16:14
Fixed by https://github.com/JuliaLang/julia/pull/28290

**Closed by fredrikekre** 2018-07-26 16:14 UTC

**Comment by nilshg** [comment] 2023-09-11 10:13
I'm running into this on 1.10beta2, full stacktrace below. Thanks to stumbling on this issue I realised that precompilation is at fault here and indeed precompiling the environment in a REPL before running the IJulia notebook works.

```
MethodError: no method matching pipe_writer(::IJulia.IJuliaStdio{Base.PipeEndpoint})
The applicable method may be too new: running in world age 31406, while current world is 31421.

Closest candidates are:
  pipe_writer(::IJulia.IJuliaStdio) (method too new to be called from this world context.)
   @ IJulia C:\Users\ngudat\.julia\packages\IJulia\Vo51o\src\stdio.jl:15
  pipe_writer(::Base.ProcessChain)
   @ Base process.jl:36
  pipe_writer(::Base.Process)
   @ Base process.jl:22
  ...


Stacktrace:
  [1] setup_stdio(stdio::IJulia.IJuliaStdio{Base.PipeEndpoint}, readable::Bool)
    @ Base .\process.jl:260
  [2] setup_stdios(f::Base.var"#784#785"{Cmd}, stdios::Vector{Union{RawFD, Base.Libc.WindowsRawSocket, IO}})
    @ Base .\process.jl:221
  [3] _spawn
    @ Base .\process.jl:138 [inlined]
  [4] open(cmds::Cmd, stdio::Base.DevNull; write::Bool, read::Bool)
    @ Base .\process.jl:393
  [5] open (repeats 2 times)
    @ Base .\process.jl:383 [inlined]
  [6] open(::Pkg.Registry.var"#19#22"{IOBuffer, Vector{UInt8}, Dict{String, String}}, ::Cmd; kwargs::@Kwargs{})
    @ Base .\process.jl:415
  [7] open
    @ Base .\process.jl:414 [inlined]
  [8] uncompress_registry(tar_gz::String)
    @ Pkg.Registry C:\Users\ngudat\AppData\Local\Programs\Julia-1.10.0-beta2\share\julia\stdlib\v1.10\Pkg\src\Registry\registry_instance.jl:261
  [9] Pkg.Registry.RegistryInstance(path::String)
    @ Pkg.Registry C:\Users\ngudat\AppData\Local\Programs\Julia-1.10.0-beta2\share\julia\stdlib\v1.10\Pkg\src\Registry\registry_instance.jl:328
 [10] reachable_registries(; depots::Vector{String})
    @ Pkg.Registry C:\Users\ngudat\AppData\Local\Programs\Julia-1.10.0-beta2\share\julia\stdlib\v1.10\Pkg\src\Registry\registry_instance.jl:434
 [11] reachable_registries
    @ Pkg.Registry C:\Users\ngudat\AppData\Local\Programs\Julia-1.10.0-beta2\share\julia\stdlib\v1.10\Pkg\src\Registry\registry_instance.jl:404 [inlined]
 [12] Pkg.Types.Context()
    @ Pkg.Types C:\Users\ngudat\AppData\Local\Programs\Julia-1.10.0-beta2\share\julia\stdlib\v1.10\Pkg\src\Types.jl:395
 [13] precompile(pkgs::Vector{Pkg.Types.PackageSpec}; io::IJulia.IJuliaStdio{Base.PipeEndpoint}, kwargs::@Kwargs{_from_loading::Bool})
    @ Pkg.API C:\Users\ngudat\AppData\Local\Programs\Julia-1.10.0-beta2\share\julia\stdlib\v1.10\Pkg\src\API.jl:150
 [14] precompile
    @ Pkg.API C:\Users\ngudat\AppData\Local\Programs\Julia-1.10.0-beta2\share\julia\stdlib\v1.10\Pkg\src\API.jl:147 [inlined]
 [15] #precompile#114
    @ Pkg.API C:\Users\ngudat\AppData\Local\Programs\Julia-1.10.0-beta2\share\julia\stdlib\v1.10\Pkg\src\API.jl:146 [inlined]
 [16] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:1957
 [17] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1806
 [18] #invoke_in_world#3
    @ Base .\essentials.jl:921 [inlined]
 [19] invoke_in_world
    @ Base .\essentials.jl:918 [inlined]
 [20] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1797
 [21] macro expansion
    @ Base .\loading.jl:1784 [inlined]
 [22] macro expansion
    @ Base .\lock.jl:267 [inlined]
 [23] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1747
 [24] #invoke_in_world#3
    @ Base .\essentials.jl:921 [inlined]
 [25] invoke_in_world
    @ Base .\essentials.jl:918 [inlined]
 [26] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1740
```

**Comment by JamesWrigley** [comment] 2025-10-28 09:25
Could you paste the stacktrace? I don't think I've ever seen this.

**Comment by JamesWrigley** [comment] 2025-10-29 18:09
Ah I see, I've also seen those errors for some other packages but I never managed to reproduce it to get a stacktrace.
