### ISSUE TITLE
message signature mismatch in some cases

### ISSUE THREAD

**Issue by shashi** [JuliaLang/IJulia.jl#421] opened 2016-05-10 11:46 UTC
I have,

```
using Interact

@manipulate for i=1:10
    i
end
```

If I move the slider, I get

```
[E 17:09:00.691 NotebookApp] Uncaught exception GET /api/kernels/0bf86635-90e3-49eb-925c-5dfd2c187150/channels?session_id=FB6EDA64ABF241B784407FBD7BC89855 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/0bf86635-90e3-49eb-925c-5dfd2c187150/channels?session_id=FB6EDA64ABF241B784407FBD7BC89855', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://localhost:8888', 'Upgrade': 'websocket', 'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Sec-Websocket-Version': '13', 'Host': 'localhost:8888', 'Sec-Websocket-Key': 'jTnLe2Oxdk/IkSaO0A/EAA==', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36', 'Connection': 'Upgrade', 'Cookie': '_ga=GA1.1.383076521.1455120339', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits'})
    Traceback (most recent call last):
      File "/home/shashi/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/tornado/web.py", line 1401, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/shashi/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/shashi/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/shashi/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 272, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "/home/shashi/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/jupyter_client/session.py", line 861, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: '<IDS|MSG>'
```

The `check` variable is `278e766a3c435d2bc489cd5f6b3211bdf24b0cae22461377b00ebca73d9742ea`

while the `signature` variable is `<IDS|MSG>` over here: https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/session.py#L858-L859

After this the Widget gets disconnected

![image](https://cloud.githubusercontent.com/assets/25916/15145233/04611294-16d2-11e6-9070-911845275da0.png)

But, If I run the `@manipulate ... end` expression after running `IJulia.set_verbose()`, this problem is not encountered. Could it be that there is a deviation in the way messages are serialized and deserialized, but IJulia.set_verbose() accidentally makes it okay?

**Comment by shashi** [comment] 2016-05-11 07:34
This is with a fresh installation of IJulia (with Conda.jl) on Julia 0.5, which actually pulls in an old release of ipywidgets...

**Comment by stevengj** [comment] 2016-05-16 20:23
`set_verbose()` just enables some printlns to the terminal window; I don't see how that could affect message signatures...

**Comment by darwindarak** [comment] 2016-06-09 20:19
I'm encountering the same problem with many code blocks that take more than a couple seconds to run.  For some reason, `set_verbose` does seem to fix the problem.

**Comment by stevengj** [comment] 2016-07-06 14:34
@shashi, any progress on this?

**Comment by maximerischard** [comment] 2016-08-10 19:14
Could there be a race condition? It looks to me like two messages are getting sent simultaneously over the same socket, and are consequently getting scrambled.

**Comment by maximerischard** [comment] 2016-08-18 20:55
I wanted to test my hypothesis, so I modified the `send_ipython` in `IJulia/src/msg.jl` function like so:
```{julia}
in_use = Dict{Ptr{Void}, Bool}()

function send_ipython(socket, m::Msg)
    if get(in_use, socket.data, false)
        println(orig_STDOUT[], "SOCKET ", socket.data, " already in use!!!!!!!!!!!")
    else
        #=println(orig_STDOUT[], "SOCKET ", socket.data, " all clear")=#
    end
    in_use[socket.data] = true
    for i in m.idents
        send(socket, i, SNDMORE)
    end
    send(socket, "<IDS|MSG>", SNDMORE)
    header = json(m.header)
    parent_header = json(m.parent_header)
    metadata = json(m.metadata)
    content = json(m.content)
    send(socket, hmac(header, parent_header, metadata, content), SNDMORE)
    send(socket, header, SNDMORE)
    send(socket, parent_header, SNDMORE)
    send(socket, metadata, SNDMORE)
    send(socket, content)
    #=println(orig_STDOUT[], "FINISHED SENDING MESSAGE ON ", socket.data)=#
    in_use[socket.data] = false
end
```
that is, I use the `in_use` dictionary to keep track of which sockets are currently sending a message.  When restarting the kernel, the problem is immediately revealed in the jupyter console:
```
[I 21:48:24.554 NotebookApp] Kernel restarted: 74a5f2b0-6d8c-4c9a-9db8-493ba5d1a5ec
Starting kernel event loops.
SOCKET Ptr{Void} @0x00007fa9ad0df200 already in use!!!!!!!!!!!
SOCKET Ptr{Void} @0x00007fa9ad0df200 already in use!!!!!!!!!!!
```

Now the funny thing is, if you uncomment the seventh line, the problem disappears:
```
[I 21:52:10.661 NotebookApp] Kernel restarted: 74a5f2b0-6d8c-4c9a-9db8-493ba5d1a5ec
SOCKET Ptr{Void} @0x00007fc69acce600 all clear
Starting kernel event loops.
SOCKET Ptr{Void} @0x00007fc69acce600 all clear
SOCKET Ptr{Void} @0x00007fc69acce600 all clear
SOCKET Ptr{Void} @0x00007fc69acce600 all clear
SOCKET Ptr{Void} @0x00007fc69abdfa00 all clear
SOCKET Ptr{Void} @0x00007fc69acce600 all clear
SOCKET Ptr{Void} @0x00007fc69acce600 all clear
SOCKET Ptr{Void} @0x00007fc69abdfa00 all clear
SOCKET Ptr{Void} @0x00007fc69acce600 all clear
SOCKET Ptr{Void} @0x00007fc69acce600 all clear
SOCKET Ptr{Void} @0x00007fc69acce600 all clear
```
So it seems that the simple additional call to `println` clears the buffer, or yields to another thread, or something like that, and so the problem disappears. I don't understand the internals of IJulia enough to diagnose the exact cause.

**Comment by stevengj** [comment] 2016-08-19 19:55
Ah, thanks @maximerischard, that explains it.   The problem that ZMQ message send and receive are operations that yield to the Julia scheduler, so other tasks can wake up and run while we are waiting for a message to send or arrive.  However, in IJulia, we potentially have multiple tasks reading/writing from the same ZMQ sockets, so this allows their messages to get out of order.

Should be straightforward to prevent the yielding, though it would be nice to prevent yielding only to other tasks talking to the same socket; let me look into it.

**Comment by stevengj** [comment] 2016-08-19 20:08
Okay, should be fixed now.  @maximerischard, can you verify that your problem goes away with the latest IJulia master (`Pkg.update(); Pkg.checkout("IJulia")`)?

**Closed** 2016-08-19 20:08 UTC

**Comment by maximerischard** [comment] 2016-08-20 07:47
I think that very much did the trick! Thank you so much for fixing this @stevengj.
