### ISSUE TITLE
Kernel won't (re)start when output should go to journal

### ISSUE THREAD

**Issue by aueelis** [JuliaLang/IJulia.jl#391] opened 2015-11-19 19:23 UTC
My jupyter instance is running in a systemd user session (two different computers running Archlinux). Normally I have no issues while using IPython or IHaskell, but IJulia doesn't work. My service file is the following:

```
[Unit]
Description=Jupyter

[Service]
Type=simple
# doesn't work with IJulia 
#ExecStart=/usr/bin/jupyter-notebook --no-browser --port=8888
# doesn't work with IJulia
#ExecStart=/bin/sh -c '/usr/bin/jupyter-notebook --no-browser --port=8888'
# works with IJulia
ExecStart=/bin/sh -c '/usr/bin/jupyter-notebook --no-browser --port=8888 > jupyter.out 2> jupyter.err'
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/home/stefan/.cabal/bin" "PYTHONPATH=/home/stefan/local/python:/home/stefan/local/python-packages"
WorkingDirectory=/home/stefan/Notebooks

[Install]
WantedBy=default.target
```

I noticed that IJulia only works, while the output of jupyter is redirected to some files and not recorded in the user journal. Otherwise, the kernel tries to restart several times and no further output from jupyter appears (also no output from IPython and IHaskell notebooks running on the same jupyter server).

```
Julia Version 0.4.1
Commit cbe1bee (2015-11-08 10:33 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libm
  LLVM: libLLVM-3.3
```

**Comment by stevengj** [comment] 2015-11-20 03:37
@Keno or @vtjnash, could there be some issue with `redirect_stdout` when the output is going to a journal via systemd?

**Comment by dev-zero** [comment] 2015-12-03 09:17
The same happens here when starting the Julia kernel via jupyterhub.
Redirecting the complete output of jupyterhub to ``/dev/null`` makes it stop crashing on my test server:

```
[Service]
# redirecting the output to work around https://github.com/JuliaLang/IJulia.jl/issues/391
ExecStart=/bin/jupyterhub --port 80 2>&1 >/dev/null
User=root
WorkingDirectory=/var/lib/jupyterhub
```

**Comment by dev-zero** [comment] 2015-12-03 09:31
Update: I can start the kernel once when redirecting the output. When I ``Close and Halt`` a notebook I am not able to restart a new kernel (even though the old one was properly terminated) until I restart jupyterhub completely.

**Comment by aueelis** [comment] 2015-12-03 12:55
@dev-zero Your redirect

    ExecStart=/bin/jupyterhub --port 80 2>&1 >/dev/null

doesn't work (check the paths `/proc/[jupyterhub's pid]/fd/1` and `/proc/[jupyterhub's pid]/fd/2`, representing stdout and stderr, resp.). Systemd interprets everything as arguments to the executable. See section "command lines" in `man systemd.service`:
> Specifically, redirection using "<", "<<", ">", and ">>", pipes using "|", running programs in the background using "&", and other elements of shell syntax are not supported.

To get redirection working, you should try to encapsulate the command into a shell like

    ExecStart=/bin/sh -c '/bin/jupyterhub --port 80 2>&1 >/dev/null'

**Comment by yuyichao** [comment] 2015-12-03 13:16
Also note that you need `>/dev/null 2>&1` instead of `2>&1 >/dev/null` to redirect both stdout and stderr

**Comment by dev-zero** [comment] 2015-12-03 13:55
@aueelis/@yuyichao Thanks a lot. Now I can repeatedly restart the Julia kernel.

**Comment by aueelis** [comment] 2015-12-06 20:53
@stevengj Is there a fix for this problem? As far as I know, the original problem still persists.

**Comment by stevengj** [comment] 2015-12-07 04:19
@aueelis, sorry, I mis-understood@dev-zero's comment and thought the problem was resolved.

**Comment by stevengj** [comment] 2019-03-27 13:41
Closing as no one seems to have reproduced this for years.

**Closed by stevengj** 2019-03-27 13:41 UTC
