### ISSUE TITLE
IJulia.notebook() should print notebook authentication URL

### ISSUE THREAD

**Issue by j605** [JuliaLang/IJulia.jl#762] opened 2018-10-21 20:18 UTC
This is useful in cases where the browser cannot be started or you are running Julia on a server and accessing the notebook locally by forwarding the connection. In this case the URL was opened on elinks which didn't amount to much.

**Comment by stevengj** [comment] 2019-03-27 13:04
Duplicate of #586

**Closed by stevengj** 2019-03-27 13:04 UTC
