### ISSUE TITLE
ZMQ error message while loading kernel for IJulia (Julia 1.0.1, Windows)

### ISSUE THREAD

**Issue by aakhmetz** [JuliaLang/IJulia.jl#759] opened 2018-10-12 01:35 UTC
Hello,

When I try to start my kernel in Jupyter, it crashes with the following error:
```
ERROR: LoadError: ZMQ.Socket has no field data
Stacktrace:
 [1] error(::Type, ::String, ::Symbol) at .\error.jl:42
 [2] getproperty(::ZMQ.Socket, ::Symbol) at C:\Users\akhme\.julia\packages\ZMQ\ABGOx\src\sockopts.jl:128
 [3] start_heartbeat(::ZMQ.Socket) at C:\Users\akhme\.julia\dev\IJulia\src\heartbeat.jl:20
 [4] init(::Array{String,1}) at C:\Users\akhme\.julia\dev\IJulia\src\init.jl:125
 [5] top-level scope at none:0
 [6] include at .\boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1041
 [8] include(::Module, ::String) at .\sysimg.jl:29
 [9] exec_options(::Base.JLOptions) at .\client.jl:229
 [10] _start() at .\client.jl:421
in expression starting at C:\Users\akhme\.julia\dev\IJulia\src\kernel.jl:9
```

It looks like it's Windows-specific, because I have no problems neither on my Mac nor Ubuntu. 

Sorry in advance if it is more related to ZMQ.jl, but I wonder if someone else had seen such error. I also checked previous issues, and I haven't found anything similar.

**Comment by stevengj** [comment] 2018-10-12 01:39
This was fixed in JuliaLang/IJulia.jl#729 — the problem is that you are using an old version of IJulia (in your dev directory) that you haven't updated.  Do
```jl
free IJulia  # stop using the dev version
up
```
at the pkg prompt.

**Closed by stevengj** 2018-10-12 01:39 UTC

**Comment by aakhmetz** [comment] 2018-10-12 01:57
@stevengj Thank you! Sorry that I missed it
