### ISSUE TITLE
I suggest to add simple installation instructions for windows users in the readme

### ISSUE THREAD

**Issue by frankhuettner** [JuliaLang/IJulia.jl#709] opened 2018-08-15 14:01 UTC
I suggest to add these lines to the readme. I think this is the simplest way to get things running. Also, it would prevent frustration from running into [#693](https://github.com/JuliaLang/IJulia.jl/issues/693) problems with the new version.

### tl;dr for Windows 10 with Anaconda
1. Have [Julia 0.6x](https://julialang.org/downloads/oldreleases.html) installed (versions 0.7 and 1.0 of Julia are currently not working with IJulia). Have [Anaconda](http://julialang.org/downloads/) installed. 
2. Find the location of Jupyter: Start the [Anaconda Prompt](https://stackoverflow.com/questions/47914980/how-to-access-anaconda-command-prompt-in-windows-10-64-bit). Run the command `where Jupyter`. The answer is the location of Jupyter, e.g. *C:\ProgramData\Anaconda3\Scripts\jupyter.exe*
3. Tell Julia where Jupyter is: Start Julia (i.e., start the Julia REPL). Run the command `ENV["JUPYTER"]="C:\\ProgramData\\Anaconda3\\Scripts\\jupyter"`  (You need to adapt the location you learned in point 2. Note that the backslashes need to be doubled, i.e. \\\ instead of \\.)
4. Install IJulia: Run `Pkg.add("IJulia")` in the Julia REPL.
5. Run Jupyter: Either from Windows Start Menu or from within Julia REPL. For the latter run `using IJulia` and `notebook()`

**Comment by stevengj** [comment] 2018-08-15 14:35
The whole point of using Conda.jl is that you don't need to have Anaconda installed.  Just do
```
Pkg.add("IJulia")
using IJulia
notebook()
```
as explained in the README.

**Comment by frankhuettner** [comment] 2018-08-15 14:54
Thanks for your fast reply.
1. What is the advantage of having a conda private to Julia next to Anaconda?
2. Is there a way to launch directly into the Jupyter-private-to-Julia via a link in the Windows start menu?

**Comment by stevengj** [comment] 2018-08-15 16:37
The advantage is that it installs automatically.

**Comment by yuvaraj119** [comment] 2018-08-15 17:40
@stevengj I tried these steps on Windows 10
Pkg.add("IJulia")
using IJulia
notebook()

But still, no output is showing.

**Comment by frankhuettner** [comment] 2018-08-15 18:47
@yuvaraj119 please be a bit more specific. What version are you using (Julia 1.0 and 0.7 https://github.com/JuliaLang/IJulia.jl/issues/693 seem to not work with IJulia for now). How far did you get. Where is no output?

**Comment by yuvaraj119** [comment] 2018-08-16 07:00
@frankhuettner sorry for not adding detailed description yes I am using Julia 1.0 and in jupyter notebook the output is not shown.

**Comment by stevengj** [comment] 2018-08-16 13:50
Duplicate of #693.

**Closed by stevengj** 2018-08-16 13:50 UTC

**Comment by w1res** [comment] 2018-10-17 19:31
I think this would be useful. I found this thread by searching for additional instructions after reading the official README. The two things I was confused about were:

1. What format do I use for giving the path (e.g., single or double backslashes, backslash or forward slash).
2. What the actual path to Jupyter is on a typical Anaconda installation.

I believe that just giving an example of `ENV["JUPYTER"]="C:\\ProgramData\\Anaconda3\\Scripts\\jupyter` like @frankhuettner said woud go a long way with minimal changes to the README.

I understand that that might be the "poweruser" option, where the user is expected to know how to do it if they are a poweruser, but in that case I believe it should be removed from the README as to not confuse non-powerusers into thinking this is something they need to do. Otherwise maybe just mention that using the Anaconda install is only intended for powerusers so that other people can just read it and move on if they don't understand it.

**Comment by GiorgioBalestrieri** [comment] 2018-10-18 09:03
Disclaimer: I'm not at all an expert in managing installations, and I probably miss a lot of context to this decision. I also trust the Julia devs to have come up with this choice for a whole lot of good reasons. I'll still try to give my view on this, based on my experience.

My two cents on this: it is complete nonsense to have a separate conda installation private to Julia. It defies the purpose of having an environment manager, creates unnecessary duplication and seriously risks creating conflicts (see below), and (I assume) adds a ton of unnecessary work to the Julia devs.

* installing anaconda is terribly easy, and if you expect the average user not to be able to do it it's probably a good idea to have them familiarize with how it works rather than providing a shortcut that will hurt them in the future. There is also plenty of information and troubleshooting on the official conda documentation and stackoverflow which can help address any corner cases. Good luck having the same for a julia-specific version.

* I have my conda (through anaconda) installation and when I installed Julia suddenly my default anaconda prompt is the one installed from Julia, which does not see the other envs I created previously.

Sorry if I'm a bit salty but the idea that a single installation just messed up my whole conda installation is beyond annoying. Knowing that the reason is probably to allow some Matlab users to use Julia without bothering to learn how conda works is the cherry on top of this. 

I personally come from Matlab (engineering background, yeah) and the thing I miss the least is the condescending way it treats its users. The Python ["we are all consenting adults"](https://mail.python.org/pipermail/tutor/2003-October/025932.html) approach is just refreshing, and empowering. Not having a CS/software engineering background is not a good reason to be treated as a toddler.

**Comment by GiorgioBalestrieri** [comment] 2018-10-18 09:30
Update: Julia messed up my default conda commands (anaconda prompt shortcuts and so on) without even asking permission. I had to reset the manually, so I can finally use them, but I'm still having trouble launching kernels in Jupyter. Just wow.

**Comment by skanskan** [comment] 2018-12-04 13:35
> @stevengj I tried these steps on Windows 10
> Pkg.add("IJulia")
> using IJulia
> notebook()
> 
> But still, no output is showing.

In order to execute those commands you first need to open Julia.
How can you do it directly from a Windows shortcut?
How would you launch Jupyterlab.

**Comment by stevengj** [comment] 2019-01-03 17:39
You have *always been able* to use IJulia, PyCall, etcetera with your own Anaconda installation.   The *only* question is what to do by default.

We used to look for a `jupyter` etcetera in the path first, but we ran into too many problems from broken Python installations.   If you are sophisticated enough to manage your own working Anaconda installation, then you should be sophisticated enough to read the directions and set and environment variable.

In any case, the latest version of IJulia doesn't use Jupyter at all for installation.   It only installs Jupyter if you run the `IJulia.notebook()` command, but if you have your own working Anaconda installation in the PATH you can just skip this and run `jupyter notebook` yourself.

**Comment by frankhuettner** [comment] 2019-01-04 15:14
@stevengj Thank you very much for adding some clarification to this discussion.
