### ISSUE TITLE
IJulia kernel no long recognizing Pkg REPL commands

### ISSUE THREAD

**Issue by erny123** [JuliaLang/IJulia.jl#1129] opened 2024-11-05 18:26 UTC
Using Julia 1.11.1 and just loaded, built, and created a kernel with: `installkernel("Julia (24 threads)", "--depwarn=no",env=Dict("JULIA_NUM_THREADS"=>"24"))`

Haven't had this issue before but when entering: `] activate .`

into a jupyter lab notebook cell I get an error: 

```
MethodError: no method matching do_cmd(::IJulia.MiniREPL, ::String; do_rethrow::Bool)
The function `do_cmd` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  do_cmd(::Pkg.REPLMode.Command, ::Any) got unsupported keyword argument "do_rethrow"
   @ Pkg ~/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/stdlib/v1.11/Pkg/src/REPLMode/REPLMode.jl:398


Stacktrace:
 [1] top-level scope
   @ In[2]:1
```

Anyone know the issue?

![Image](https://github.com/user-attachments/assets/54df2e5f-56e3-4c82-8d8d-b46e03465618)

**Comment by nilshg** [comment] 2024-11-06 10:52
Duplicate of #1119 and already addressed in latest release.

**Comment by erny123** [comment] 2024-11-06 16:45
Hi Paul, yes someone else was parked in my spot so I ended up parking in
the other spot.
It was late. Sorry about that!

**Closed** 2024-11-12 01:57 UTC
