### ISSUE TITLE
IJulia Installation on Windows

### ISSUE THREAD

**Issue by ericjang** [JuliaLang/IJulia.jl#363] opened 2015-09-27 13:13 UTC
I am using Windows 10 and Anaconda with julia-0.5.0. I previously had IJulia installed and working, but then somehow calling Pkg.update() broke my installation.

Here is the error message:

Installing julia kernelspec julia-0.5
===================================================[ ERROR: IJulia ]====================================================

LoadError: could not spawn `jupyter-kernelspec install --replace --user julia-0.5`: no such file or directory (ENOENT)
while loading C:\Users\eric\.julia\v0.5\IJulia\deps\build.jl, in expression starting on line 101

========================================================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: IJulia had build errors.

 - packages with build errors remain installed in C:\Users\eric\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("IJulia")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================
INFO: Package database updated

Running ```Pkg.build("IJulia")``` produced the same error.

**Comment by dhoegh** [comment] 2015-09-27 14:54
I have proposed a fix in #364 could you check if it works?

**Comment by ericjang** [comment] 2015-09-27 16:29
Simply patching those 2 lines didn't seem to work for me:

I ran Windows Powershell with administrator and did ```pip install --upgrade jupyter``` (I'm using Anaconda), then ran ```jupyter kernelspec``` in Windows powershell but got 

"jupyter: kernelspec is not a Jupyter command"

**Comment by dhoegh** [comment] 2015-09-27 16:36
Ok. Have you tried the orginal build script after  `pip install --upgrade jupyter`? Do excuting `jupyter-kernelspec --version` work?

**Comment by ericjang** [comment] 2015-09-27 16:39
Yep, it yields the error above (kernelspec is not a Jupyter command).
I also get this error when I run ```jupyter kernelspec --version``` in Powershell.

Do I need to be using the dev branch of Jupyter notebook for kernelspec to show up?

**Comment by dhoegh** [comment] 2015-09-27 16:41
Sorry the comment split the line unfortunate it is `jupyter-kernelspec  --version` where jupyter and kernerlspec joined by `-`.

**Comment by ericjang** [comment] 2015-09-27 16:48
Unfortunately, that doesn't work either :/

```
PS C:\Users\eric> jupyter-kernelspec --version
jupyter-kernelspec : The term 'jupyter-kernelspec' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ jupyter-kernelspec --version
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (jupyter-kernelspec:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by dhoegh** [comment] 2015-09-27 16:50
Do the command work in cmd instead of powershell?

**Comment by ericjang** [comment] 2015-09-27 16:53
tried that, doesn't work either.

```jupyter --version``` returns 4.0.6

Strangely enough, running ```jupyter -h``` lists the following subcommands:
```
Available subcommands: console kernelspec migrate nbconvert nbextension
notebook qtconsole trust
```

**Comment by dhoegh** [comment] 2015-09-27 17:12
Hmm. I am indeed confused now. I think the only resolution to this is to wait for https://github.com/jupyter/jupyter_core/pull/62 or downgrade to IPython3. Alternative you could let IJulia use the Conda package which can be done by:
```julia
julia> ENV["JUPYTER"]=""
julia> Pkg.build("IJulia")
```

**Comment by stevengj** [comment] 2015-09-27 23:31
If `jupyter-kernelspec` is not in the PATH either, that sounds like it is a different problem from jupyter/jupyter_core#62 ... sounds like a problem with your Anaconda installation?

**Comment by dhoegh** [comment] 2015-09-28 05:23
It sounds like what **minrk** describes here, https://github.com/jupyter/notebook/issues/448#issuecomment-143172921 where https://github.com/jupyter/jupyter_core/pull/62  is the PR for fixing the issue.

**Comment by n-s-k** [comment] 2015-09-30 14:27
I had the very same issue, using `jupyter --version` 4.0.6: 

`jupyter: 'kernelspec' is not a Jupyter command` 

If I try to `Pkg.build('IJulia')`: 

 ` could not spawn jupyter-kernelspec install --replace --user julia-0.5: no such file or directory (ENOENT)`. 

My understanding is that although `Anaconda\Scripts` is in the PATH and contains `jupyter-kernelspec`, this latter is not a windows executable. 

As a temporary workaround, I replaced line 101 of build.jl with:
```julia
run(`python C:\\Anaconda\\Scripts\\$jupyter-kernelspec install --replace --user $juliakspec`) 
```
and ran `Pkg.build('IJulia')` again. 

I still don't get it and I'm certain there is a cleaner solution.

**Comment by stevengj** [comment] 2015-09-30 15:21
@n-s-k, does `jupyter-kernelspec --version` work in `run`?

**Comment by n-s-k** [comment] 2015-09-30 15:37
```julia
julia> run(`jupyter --version`)
4.0.6
julia> run(`jupyter-console --version`)
4.0.2
julia> run(`jupyter-notebook --version`)
4.0.5
julia> run(`jupyter-kernelspec --version`)
ERROR: could not spawn `jupyter-kernelspec --version`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:217 (repeats 2 times)
```

![image](https://cloud.githubusercontent.com/assets/7289762/10197863/785aee68-6791-11e5-9b89-286fb81a8818.png)

**Comment by stevengj** [comment] 2015-09-30 15:45
What is `jupyter-kernelspec`?  A batch file?  (If so, why doesn't it end with `.bat`?)

**Comment by stevengj** [comment] 2015-09-30 15:48
On my Mac, `jupyter-kernelspec` is
```
#!/Users/stevenj/anaconda/bin/python
from jupyter_client.kernelspecapp import KernelSpecApp

def main():
    KernelSpecApp.launch_instance()

if __name__ == '__main__':
    main()
```
but I guess Windows doesn't know how to spawn this.

**Comment by n-s-k** [comment] 2015-09-30 15:49
On Windows, `jupyter-kernelspec` is:
```python
#!C:\Anaconda\python.exe
from jupyter_client.kernelspecapp import KernelSpecApp

def main():
    KernelSpecApp.launch_instance()

if __name__ == '__main__':
    main()
```

yep... a python script and Windows is clueless.

**Comment by stevengj** [comment] 2015-09-30 15:50
Okay, this should be a straightforward fix.  We just need to find the correct path of `jupyter-kernelspec` and run it with Python.

**Comment by stevengj** [comment] 2015-09-30 18:23
Okay, it should be fixed now.  Please do `Pkg.checkout("IJulia"); Pkg.build("IJulia")` and confirm that it works.  Once you confirm, I will tag a new version.

**Closed** 2015-09-30 18:22 UTC

**Comment by n-s-k** [comment] 2015-09-30 18:43
Confirmed.

**Comment by ericjang** [comment] 2015-09-30 19:44
This works for me too. Thanks!

**Comment by stevengj** [comment] 2015-09-30 20:46
Great, tagged as IJulia 1.1.2.

**Comment by tkelman** [comment] 2015-10-04 03:55
I'm hitting this with the latest tag.
```
INFO: Found Jupyter version 4.0.6: C:\Users\Tony\.julia\v0.4\Conda\deps\usr\Scripts\jupyter
Writing IJulia kernelspec to julia-0.4\kernel.json ...
Installing julia kernelspec julia-0.4
jupyter: 'kernelspec' is not a Jupyter command
C:\Users\Tony\.julia\v0.4\Conda\deps\usr\python.exe: can't open file 'C:\Users\Tony\.julia\v0.4\Conda\deps\usr\Scripts\jupyter-kernelspec': [Errno 2] No such file or directory
===============================[ ERROR: IJulia ]================================

LoadError: failed process: Process(`'C:\Users\Tony\.julia\v0.4\Conda\deps\usr\python.exe' 'C:\Users\Tony\.julia\v0.4\Conda\deps\usr\Scripts\jupyter-kernelspec' install --replace --user julia-0.4`, ProcessExited(2)) [2]
while loading C:\Users\Tony\.julia\v0.4\IJulia\deps\build.jl, in expression starting on line 118
```

`C:\Users\Tony\.julia\v0.4\Conda\deps\usr\Scripts` has a `jupyter-kernelspec.exe` and a `jupyter-kernelspec-script.py`, but no plain `jupyter-kernelspec` without an extension. It looks like this may differ depending on anaconda or jupyter version?

**Comment by stevengj** [comment] 2015-10-05 20:14
Hmm, do we need a similar fix on windows to get `notebook()` working?

**Comment by minrk** [comment] 2015-10-10 11:46
I believe several of these issues (esp #368) were caused by improper packaging of entrypoints in the Jupyter projects on Windows. Most of the entrypoints were fixed relatively promptly during the summer, but `jupyter-client` never got a release with the fix until 4.1, this week. I thought we had done that a while ago, but we hadn't. Hopefully this will be better behaved with the 4.1 update to jupyter-client.

**Comment by stevengj** [comment] 2015-10-10 12:08
Thanks, @minrk.  We will keep the workarounds in for quite some time, to support older installations, but it is great to hear that this has been fixed.

**Comment by bsouthwood** [comment] 2016-04-26 19:21
On Windows 7, 64-bit. 
Installed Julia v0.4.5 -> Installed Anaconda (Python 3, 64 bit)
ran Pkg.add("IJulia") and it failed.
I installed Julia v0.5 (unstable version) and it worked.

Here is the error:

INFO: Downloading miniconda installer ...
INFO: Installing miniconda ...
===============================[ ERROR: IJulia ]================================

LoadError: could not spawn `'C:\Users\bsouthwood\.julia\v0.4\Conda\deps\usr\installer.exe' /S /AddToPath=0 /RegisterPython=0 '/D=C:\Users\bsouthwood\.julia\v0.4\Conda\deps\usr'`: unknown error (UNKNOW
N)
while loading C:\Users\bsouthwood\.julia\v0.4\IJulia\deps\build.jl, in expression starting on line 35

**Comment by stevengj** [comment] 2016-04-26 21:15
@bsouthwood, that should be reported at Conda.jl

**Comment by bsouthwood** [comment] 2016-04-26 22:32
Apologiea, i'm a noob.. I checked line 35 of the build.ml file and it contained a jupytyr variable so i thought it was related to this threas.

**Comment by hayd** [comment] 2016-05-21 18:21
It looks like IPython.jl is using the globally installed jupyter/ipython (rather than one locally installed from Conda.jl). This means that if you have ipython installed but *not* jupyter (specifically jupyter_client, though with just that `notebook()` will just immediately exit) you'll get the error noted above.

**Comment by stevengj** [comment] 2016-05-23 14:19
@bsouthwood, to simplify installation, do `ENV["JUPYTER"]=""; Pkg.build("IJulia")` ... this will use the Conda Jupyter and will auto-install everything for you.

**Comment by bsouthwood** [comment] 2016-05-23 14:40
Thanks.
