### ISSUE TITLE
Running any cell in IJulia notebook gives bytestring(zmsg::Message) deprecated warning

### ISSUE THREAD

**Issue by c123w** [JuliaLang/IJulia.jl#443] opened 2016-08-06 15:58 UTC
If I make a cell with (for example) a=1, and then run it, I get an output of 1 as expected, but I also get the following error message:

```
WARNING: bytestring(zmsg::Message) is deprecated, use unsafe_string(zmsg::Message) instead.
 in depwarn at ./deprecated.jl:73
while loading /home/johnsmith/.julia/v0.4/IJulia/src/kernel.jl, in expression starting on line 35
WARNING: bytestring(zmsg::Message) is deprecated, use unsafe_string(zmsg::Message) instead.
 in depwarn at ./deprecated.jl:73
while loading /home/johnsmith/.julia/v0.4/IJulia/src/kernel.jl, in expression starting on line 35
WARNING: bytestring(zmsg::Message) is deprecated, use unsafe_string(zmsg::Message) instead.
 in depwarn at ./deprecated.jl:73
while loading /home/johnsmith/.julia/v0.4/IJulia/src/kernel.jl, in expression starting on line 35
WARNING: bytestring(zmsg::Message) is deprecated, use unsafe_string(zmsg::Message) instead.
 in depwarn at ./deprecated.jl:73
while loading /home/johnsmith/.julia/v0.4/IJulia/src/kernel.jl, in expression starting on line 35
WARNING: bytestring(zmsg::Message) is deprecated, use unsafe_string(zmsg::Message) instead.
 in depwarn at ./deprecated.jl:73
while loading /home/johnsmith/.julia/v0.4/IJulia/src/kernel.jl, in expression starting on line 35
WARNING: bytestring(zmsg::Message) is deprecated, use unsafe_string(zmsg::Message) instead.
 in depwarn at ./deprecated.jl:73
while loading /home/johnsmith/.julia/v0.4/IJulia/src/kernel.jl, in expression starting on line 35
WARNING: bytestring(zmsg::Message) is deprecated, use unsafe_string(zmsg::Message) instead.
 in depwarn at ./deprecated.jl:73
while loading /home/johnsmith/.julia/v0.4/IJulia/src/kernel.jl, in expression starting on line 35
```
Why am I getting this error? Is it actually anything to worry about? (and if not, how can I suppress this warning?)

I'm  running a fresh install of Julia/IJulia (0.4.6) on Ubuntu 16.

**Comment by jmbromley** [comment] 2016-08-07 14:26
I get the same problem with latest stable Jupyter from pip and Julia from Debian sid (IJulia installed by pkg.add("IJulia"))

**Comment by stevengj** [comment] 2016-08-07 14:50
It's not an error, it's a warning, and you must be using a Julia 0.5 pre-release, not Julia 0.4.   It should be fixed by JuliaLang/ZMQ.jl#108, so if you do a `Pkg.update()` the warning should go away.

**Closed by stevengj** 2016-08-07 14:50 UTC

**Comment by jmbromley** [comment] 2016-08-07 16:48
That was my thought too, that debian sid must have packaged a 0.5 prerelease, but I've checked /usr/share/julia/base/deprecated.jl in my install and it definitely doesn't have the deprecated bytestring entries that are present in the 0.5 series... so very strange.  Also Pkg.update() says there is nothing to update --- presumably because it too thinks I am on the 0.4 series not the prerelease?  I'll try and force an install of ZMQ from master and see if that fixes it.  Very confused as to what Debian could have done, it was working a few weeks ago...

**Comment by jmbromley** [comment] 2016-08-07 18:14
OK, it's definitely not a Julia prerelease and it's not Debian's fault either.  It's caused by the last commit to ZMQ (14 days ago JuliaLang/ZMQ.jl#107).  The warnings can be avoided by downgrading to previous ZMQ with Pkg.pin("ZMQ",v"0.3.2").  I'll file an issue against ZMQ.  I know it's just a warning, but it is so verbose and profuse that it makes using the jupyter notebook a very awkward experience.

**Comment by tkelman** [comment] 2016-08-07 18:40
The deprecatrd method here is bytestring on a ZMQ.jl type, not a base type. So we could either make that deprecation 0.5-only, or update here to use the new name.
