### ISSUE TITLE
no output in jupyter when the kernel is julia1.0

### ISSUE THREAD

**Issue by lujianok** [JuliaLang/IJulia.jl#707] opened 2018-08-14 02:33 UTC
After I run a cell, no output appears.

**Comment by strickek** [comment] 2018-08-14 05:07
On Windows?

**Comment by lujianok** [comment] 2018-08-14 07:00
Windows 10

**Comment by stevengj** [comment] 2018-08-15 14:37
Duplicate of #693.

**Closed by stevengj** 2018-08-15 14:37 UTC

**Comment by lujianok** [comment] 2018-08-16 00:59
NO, I scroll back to Julia 0.6.4.

**Comment by stevengj** [comment] 2018-08-16 16:11
Please file a new issue, then, specify Julia 0.6, give your system information and the output of `Pkg.build("IJulia")`, and try the https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems suggestion.
