### ISSUE TITLE
Win10, failed to install IJulia

### ISSUE THREAD

**Issue by ysgclight** [JuliaLang/IJulia.jl#764] opened 2018-10-21 23:30 UTC
Error is like this, and I can't build IJulia. Do you guys have any suggestions?

julia> Pkg.build("IJulia")
  Building Conda ──→ `C:\Users\Ha\.julia\packages\Conda\uQitS\deps\build.log`
  Building ZMQ ────→ `C:\Users\Ha\.julia\packages\ZMQ\ABGOx\deps\build.log`
  Building MbedTLS → `C:\Users\Ha\.julia\packages\MbedTLS\CwGUN\deps\build.log`
  Building IJulia ─→ `C:\Users\Ha\.julia\packages\IJulia\0cLgR\deps\build.log`
┌ Error: Error building `IJulia`:
│ ERROR: could not load library "C:\Users\Ha\AppData\Local\Julia-1.0.1\lib\julia\sys.dll"
│ The paging file is too small for this operation to complete.
│
│ ERROR: LoadError: IOError: write: broken pipe (EPIPE)
│ Stacktrace:
│  [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at .\event.jl:196
│  [2] wait() at .\event.jl:255
│  [3] uv_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at .\stream.jl:786
│  [4] unsafe_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at .\stream.jl:834
│  [5] unsafe_write at .\io.jl:225 [inlined]
│  [6] macro expansion at .\gcutils.jl:87 [inlined]
│  [7] write(::Pipe, ::String) at .\strings\io.jl:164
│  [8] create_expr_cache(::String, ::String, ::Array{Pair{Base.PkgId,UInt64},1}, ::Base.UUID) at .\loading.jl:1116
│  [9] macro expansion at .\logging.jl:308 [inlined]
│  [10] compilecache(::Base.PkgId, ::String) at .\loading.jl:1187
│  [11] _require(::Base.PkgId) at .\logging.jl:311
│  [12] require(::Base.PkgId) at .\loading.jl:855
│  [13] macro expansion at .\logging.jl:311 [inlined]
│  [14] require(::Module, ::Symbol) at .\loading.jl:837
│  [15] include at .\boot.jl:317 [inlined]
│  [16] include_relative(::Module, ::String) at .\loading.jl:1041
│  [17] include(::Module, ::String) at .\sysimg.jl:29
│  [18] top-level scope at none:2
│  [19] eval at .\boot.jl:319 [inlined]
│  [20] eval(::Expr) at .\client.jl:389
│  [21] top-level scope at .\none:3
│ in expression starting at C:\Users\Ha\.julia\packages\Conda\uQitS\src\Conda.jl:19
│ ERROR: LoadError: Failed to precompile Conda [8f4d0f93-b110-5947-807f-2305c1781a2d] to C:\Users\Ha\.julia\compiled\v1.0\Conda\WZE3U.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] macro expansion at .\logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1187
│  [4] _require(::Base.PkgId) at .\logging.jl:311
│  [5] require(::Base.PkgId) at .\loading.jl:855
│  [6] macro expansion at .\logging.jl:311 [inlined]
│  [7] require(::Module, ::Symbol) at .\loading.jl:837
│  [8] include at .\boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1041
│  [10] include(::Module, ::String) at .\sysimg.jl:29
│  [11] include(::String) at .\client.jl:388
│  [12] top-level scope at none:0
│ in expression starting at C:\Users\Ha\.julia\packages\IJulia\0cLgR\deps\build.jl:2
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1069

**Comment by stevengj** [comment] 2018-10-23 18:51
Duplicate of #763

**Closed by stevengj** 2018-10-23 18:51 UTC
