### ISSUE TITLE
Kernel on Jupyter Notebook constantly dies 

### ISSUE THREAD

**Issue by janmazza** [JuliaLang/IJulia.jl#1022] opened 2021-08-24 09:09 UTC
Hi everybody, 

I am a beginner and it is the first time I post here, so I apologize in advance for any mistake I might make. 

I use jupyter notebooks for both Python and Julia - never had any issue. I recently updated Julia to version 1.6.2. Since then, whenever I open old julia scripts or start a new one, the connection to the kernel fails until the kernel is declared dead. 
I tried to find a solution on this and other fora, but nothing has worked. I uninstalled and re-installed Julia twice: in both occasions, the kernel occasionally worked for the very first time I opened a file, but not anymore as soon as I launched jupyter a second time. 

This is what anaconda says:

```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x26f3fa5 -- jl_mutex_unlock at /cygdrive/c/buildbot/worker/package_win64/build/src\locks.h:134 [inlined]
jl_get_library_ at /cygdrive/c/buildbot/worker/package_win64/build/src\runtime_ccall.cpp:52
in expression starting at C:\Users\janma\.julia\packages\IJulia\IDNmS\src\kernel.jl:24
[I 11:02:09.635 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
```
Thanks a lot for any help you could provide me on this!

**Comment by SanjayMoorjani** [comment] 2021-09-06 18:32
I'm facing the same issue. Updated to Julia 1.6.2 as FFTW pkg has been upgraded only for Julia 1.6+ but now stuck with kernel dying challenge.

Error: 

Kernel Restarting
The kernel for c/a/b.ipynb appears to have died. It will restart automatically.

**Comment by GitTorres** [comment] 2021-11-23 06:27
The same thing is happening to me with the Julia kernel in the Jupyter data science notebook that's on Docker hub.  I'm following the dataframes.jl tutorial notebook from Juliacon 2021, and the kernel has died 5 times today.   Sometimes a dialog box pops up letting me know.  Other times it silently dies.

Container Log after the latest death:
```
[I 2021-11-23 06:19:55.580 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports

kernel dc482689-f97f-47ee-8129-77d91003bfc4 restarted
```

Julia v. 1.6.3.

**Comment by lewisl** [comment] 2021-12-03 22:35
Lots of things die with the latest IJulia, especially with the Julia 1.7 build for Apple Silicon.

**Comment by janxkoci** [comment] 2022-02-21 15:39
So this is why IJulia never worked for me?

I started to explore Julia recently, after years of using R. I used `conda` to create a new env for `julia` and installed `IJulia` from within julia session, using its package manager (as I haven't found ijulia in any conda channel). I have `jupyter` in the `base` env of conda (for use with all my R envs), so julia didn't need to install it and it opened a notebook after first launch (with `notebook()`).

However, the jupyter notebook never connects to the ijulia kernel, and after a while the kernel dies. Pretty much the same experience with jupyter console or qtconsole. So for now I only play with it in the terminal using the default repl.

I'm on Ubuntu-based linux btw, using recent Intel core i5 cpu. The julia installed by conda is 1.7.2.

**Comment by Balinus** [comment] 2022-04-08 19:15
Same problem here : kernel never connect and keeps crashing. What kind of debug would be needed in terms of information?

**Comment by stevengj** [comment] 2022-04-08 22:09
I'm going to close this issue because it's not a single issue — any number of things could cause the "kernel died" message, so it's not useful to have a single issue.

Most likely Jupyter or Julia is misconfigured in some way.   In order to debug such a problem you need the full error message (printed at the terminal).  See also the [troubleshooting](https://julialang.github.io/IJulia.jl/stable/manual/troubleshooting/) information and in particular the section on [Debugging IJulia problems](https://julialang.github.io/IJulia.jl/stable/manual/troubleshooting/#Debugging-IJulia-problems) to get more verbose error messages.

If you can't figure it out, I would suggest asking on [Julia Discourse](https://discourse.julialang.org/) as your first resort, as it's most likely a configuration error and not a bug in IJulia per se.

**Closed by stevengj** 2022-04-08 22:09 UTC

**Comment by lewisl** [comment] 2022-04-13 15:56
Thanks.  Will give this a try and report back.

- Lewis

On Apr 13, 2022, at 6:07 AM, Philippe Roy ***@***.***> wrote:

﻿

I solved my specific problem. It was related to a config problem in ~/.julia/config/startup.ijulia.jl. Cleaning up this file to a barebone config using only Revise.jl was enough to solve it. Hope it helps other people. I agree it is very hard to debug. Especially since I am connecting to a remove jupyter through ssh tunneling across 2-3 nodes 😄

try
    using Revise
catch e
    @warn "Error initializing Revise" exception=(e, catch_backtrace())
end

**Comment by lewisl** [comment] 2022-04-13 21:06
Reporting back:

I don’t have a startup file for IJulia at all.

My problem with jupyter instability is using the internal notebook implementation of Visual Studio Code, which communicates with Julia through the language server rather than via Python to IJulia (both are supported).

The Visual Studio Code internal notebook code is both slow and unstable.

From: Philippe Roy ***@***.***>
Reply-To: "JuliaLang/IJulia.jl" ***@***.***>
Date: Wednesday, April 13, 2022 at 6:07 AM
To: "JuliaLang/IJulia.jl" ***@***.***>
Cc: Lewis Levin ***@***.***>, Comment ***@***.***>
Subject: Re: [JuliaLang/IJulia.jl] Kernel on Jupyter Notebook constantly dies (#1022)


I solved my specific problem. It was related to a config problem in ~/.julia/config/startup.ijulia.jl. Cleaning up this file to a barebone config using only Revise.jl was enough to solve it. Hope it helps other people. I agree it is very hard to debug. Especially since I am connecting to a remove jupyter through ssh tunneling across 2-3 nodes 😄

try



    using Revise



catch e



    @warn "Error initializing Revise" exception=(e, catch_backtrace())



end

**Comment by janxkoci** [comment] 2022-04-19 12:33
I tried the steps to enable debugging info, but got this:

```
julia> ENV["IJULIA_DEBUG"]=true
true

julia> Pkg.build("IJulia")
ERROR: UndefVarError: Pkg not defined
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1

```

**Comment by lewisl** [comment] 2022-06-07 19:33
Even though this is very old, I solved the problem and leave this information for anyone who finds this issue via search.

My problem was a cell that ran code that used Plots. Plots takes a _very_ long time to build and jupyter will mark the kernel as idle and terminate it if the kernel takes too long to respond.

I changed these settings in ```jupyter_notebook_config.py```:
```
## Timeout (in seconds) after which a kernel is considered idle and ready to be
#  culled.
#  See also: MappingKernelManager.cull_idle_timeout
c.GatewayKernelManager.cull_idle_timeout = 20  # uncomment the line and use a suitable value

## Timeout for giving up on a kernel (in seconds).
#  See also: MappingKernelManager.kernel_info_timeout
c.GatewayKernelManager.kernel_info_timeout = 20  # uncomment the line and use a suitable value
```
20 seconds is a long enough time it seems.  Haven't had kernel's dying on me since.

**Comment by janxkoci** [comment] 2022-06-07 20:11
I have the kernel dying even with just `1+1`. No code ever runs, the kernel dies immediatelly after launching the notebook. I tried launching notebooks from within a julia session as well as from terminal and creating new julia notebook that way. Neither ever worked.

**Comment by lewisl** [comment] 2022-06-08 21:43
~/.jupyter

From: Philippe Roy ***@***.***>
Reply-To: "JuliaLang/IJulia.jl" ***@***.***>
Date: Wednesday, June 8, 2022 at 12:56 PM
To: "JuliaLang/IJulia.jl" ***@***.***>
Cc: Lewis Levin ***@***.***>, Comment ***@***.***>
Subject: Re: [JuliaLang/IJulia.jl] Kernel on Jupyter Notebook constantly dies (#1022)


jupyter_notebook_config.py

Where is it located? Thanks!

**Comment by janxkoci** [comment] 2022-09-26 11:26
FYI I solved my issue by completely removing julia installed by conda and instead downloading and installing the official version from the website. After that (and cleaning any conda folders that were interfering with the new install) ijulia started working fine and I can now finally use it in jupyter notebook, so I can start learning the dang language :smile:
