### ISSUE TITLE
Error trying to install IJulia via console.

### ISSUE THREAD

**Issue by snowzone5** [JuliaLang/IJulia.jl#1065] opened 2023-02-06 18:46 UTC
1. The output of `versioninfo()`

julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, ivybridge)
  Threads: 1 on 12 virtual cores

3. How you installed Julia

I installed julia-1.8.5-win64.exe from: https://julialang.org/downloads/

First attachment (julia-err.txt) , was my first attempt
[julia-err1.txt](https://github.com/JuliaLang/IJulia.jl/files/10668133/julia-err1.txt)

I read in a forum where deleting the General registry helped some.

Second attachment: julia-err2.txt was my second attempt after deleting the General registry
[julia-err2.txt](https://github.com/JuliaLang/IJulia.jl/files/10668152/julia-err2.txt)

**Comment by stevengj** [comment] 2023-02-06 19:16
Please [submit a bug report to Julia itself](https://github.com/JuliaLang/julia/issues) or ask [on the Julia Discourse forum](https://discourse.julialang.org/).  If Julia is crashing with an `EXCEPTION_ACCESS_VIOLATION` when you do a `Pkg.add`, that's not something specific to IJulia.   I would also just try re-installing Julia itself, in case you have a broken/corrupted Julia installation

Also, don't put your error messages into text files.  Just paste them directly into the issue [quoted with ```` ``` ```` triple backticks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks):
```
julia> using Pkg

julia> Pkg.add("IJulia")
  Installing known registries into `C:\Users\snowz\.julia`
    Updating registry at `C:\Users\snowz\.julia\registries\General.toml`
   Resolving package versions...

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ff905e952a2 -- fs__chmod at /workspace/srcdir/libuv\src/win\fs.c:2372
in expression starting at REPL[2]:1
fs__chmod at /workspace/srcdir/libuv\src/win\fs.c:2372
uv__fs_work at /workspace/srcdir/libuv\src/win\fs.c:3218
uv_fs_chmod at /workspace/srcdir/libuv\src/win\fs.c:3774
```

**Closed by stevengj** 2023-02-06 19:16 UTC

**Comment by stevengj** [comment] 2023-02-06 21:54
Looks like this is https://github.com/JuliaLang/julia/issues/41642
