### ISSUE TITLE
Failed to install IJulia

### ISSUE THREAD

**Issue by ArcherWoo** [JuliaLang/IJulia.jl#779] opened 2018-11-13 20:57 UTC
![screen shot 2018-11-14 at 7 55 07 am](https://user-images.githubusercontent.com/43308918/48442558-a748ee80-e7e2-11e8-85ca-d1f478efc0ba.png)
![screen shot 2018-11-14 at 7 54 41 am](https://user-images.githubusercontent.com/43308918/48442600-ba5bbe80-e7e2-11e8-9d64-9621e6473ae4.png)

I tried to run IJulia in JuliaPro 1.0 but failed. I reinstalled Julia, and JuliaPro, but still doesn't work.

**Comment by stevengj** [comment] 2018-11-14 03:08
The error message says that your Conda installation got corrupted, possibly because you force-terminated it in the middle of the installation.  You might need to delete JuliaPro and re-install.

**Comment by ArcherWoo** [comment] 2018-11-14 15:47
> The error message says that your Conda installation got corrupted, possibly because you force-terminated it in the middle of the installation. You might need to delete JuliaPro and re-install.

Hi Steven
Thank you to reply. I follow what you said to delete JuliaPro and re-install. But, it still doesn't work.
Do you know what's wrong here?
Thank you so much
Best,

![screen shot 2018-11-15 at 2 40 10 am](https://user-images.githubusercontent.com/43308918/48493763-9cdd3200-e880-11e8-8e05-ad4b6cad6043.png)
![screen shot 2018-11-15 at 2 43 35 am](https://user-images.githubusercontent.com/43308918/48493767-9fd82280-e880-11e8-969a-5d9339a2c053.png)
![screen shot 2018-11-15 at 2 42 57 am](https://user-images.githubusercontent.com/43308918/48493774-a23a7c80-e880-11e8-961d-958d773e7885.png)

**Comment by stevengj** [comment] 2018-11-14 17:49
The error message says you have a permissions error in `/Users/ArcherWoo/.jupyter`.

That usually means that you created this directory (or something in it) without write permissions (e.g. as root or something) somehow.   Try removing your `.jupyter` directory and try again.

(It's better to just copy and paste the terminal output, quoted with backticks ` ``` `, than to post screenshots. Screenshots are hard to read, cannot be searched, and cannot be quoted easily.)

**Comment by patdub** [comment] 2018-11-14 23:06
I had a similar problem with Julia 1.0.2.

The error message, in my case, was that it was not possible to write a new kernel in User/.../AppData/Roaming/Jupyter/kernels/julia-1.0.
The folder was in read only. I change the flag and try a new build IJulia and it solve the problem. After building, le folder was again with a read only permission.

Patrick.

**Comment by patdub** [comment] 2018-11-15 16:28
I am on windows and I build IJulia using the package manager.
My account is administrator but I don't know if I have always the administrator privileges all the time.

**Comment by xiaodaigh** [comment] 2018-11-20 08:56
When I tried to build IJulia on Windows 10 with Julia 1.0.2 I get this error. And running it in admin mode doesn't change the outcome. I only have one account which is admin account.

> julia> Pkg.build("IJulia")
>   Building Conda ──→ `C:\Users\RTX2080\.julia\packages\Conda\uQitS\deps\build.log`
>   Building ZMQ ────→ `C:\Users\RTX2080\.julia\packages\ZMQ\ABGOx\deps\build.log`
>   Building MbedTLS → `C:\Users\RTX2080\.julia\packages\MbedTLS\r1Ufc\deps\build.log`
>   Building IJulia ─→ `C:\Users\RTX2080\.julia\packages\IJulia\DL02A\deps\build.log`
> ┌ Error: Error building `IJulia`:
> │ Solving environment: ...working... done
> │
> │ # All requested packages already installed.
> │
> │ [InstallKernelSpec] Removing existing kernelspec in C:\Users\RTX2080\AppData\Roaming\jupyter\kernels\julia-1.0
> │ [WinError 5] Access is denied: 'C:\\Users\\RTX2080\\AppData\\Roaming\\jupyter\\kernels\\julia-1.0\\logo-32x32.png'
> │ [InstallKernelSpec] Removing existing kernelspec in C:\Users\RTX2080\AppData\Roaming\jupyter\kernels\julia-1.0
> │ [WinError 5] Access is denied: 'C:\\Users\\RTX2080\\AppData\\Roaming\\jupyter\\kernels\\julia-1.0\\logo-32x32.png'
> │ [ Info: Installing Jupyter via the Conda package.
> │ [ Info: Running `conda install -y jupyter` in root environment
> │ [ Info: Found Jupyter version 4.4.0: C:\Users\RTX2080\.julia\conda\3\Scripts\jupyter
> │ [ Info: Installing Julia kernelspec julia-1.0
> │ ERROR: LoadError: failed process: Process(`'C:\Users\RTX2080\.julia\conda\3\python.exe' 'C:\Users\RTX2080\.julia\conda\3\Scripts\jupyter-kernelspec-script.py' install --replace --user 'C:\Users\RTX2080\AppData\Local\Temp\julia-1.0'`, ProcessExited(1)) [1]
> │ Stacktrace:
> │  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
> │  [2] pipeline_error at .\process.jl:705 [inlined]
> │  [3] #run#504(::Bool, ::Function, ::Cmd) at .\process.jl:663
> │  [4] run at .\process.jl:661 [inlined]
> │  [5] #installkernel#4(::String, ::Function, ::String) at C:\Users\RTX2080\.julia\packages\IJulia\DL02A\deps\kspec.jl:85
> │  [6] installkernel(::String) at C:\Users\RTX2080\.julia\packages\IJulia\DL02A\deps\kspec.jl:36
> │  [7] top-level scope at logging.jl:308
> │  [8] top-level scope at logging.jl:307
> │  [9] top-level scope at C:\Users\RTX2080\.julia\packages\IJulia\DL02A\deps\build.jl:41
> │  [10] include at .\boot.jl:317 [inlined]
> │  [11] include_relative(::Module, ::String) at .\loading.jl:1044
> │  [12] include(::Module, ::String) at .\sysimg.jl:29
> │  [13] include(::String) at .\client.jl:392
> │  [14] top-level scope at none:0
> │ in expression starting at C:\Users\RTX2080\.julia\packages\IJulia\DL02A\deps\build.jl:9
> └ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1097

**Comment by strickek** [comment] 2018-11-20 18:37
First I had the problem after update(). Then I installed Julia new, but I have also problem to install IJulia:

'''
julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD A10-7800 Radeon R7, 12 Compute Cores 4C+8G
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, bdver3)

(v1.0) pkg> add IJulia
  Updating registry at `C:\Users\Klaus\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `C:\Users\Klaus\.julia\environments\v1.0\Project.toml`
  [7073ff75] + IJulia v1.14.1
  Updating `C:\Users\Klaus\.julia\environments\v1.0\Manifest.toml`
  [b99e7846] + BinaryProvider v0.5.2
  [34da2185] + Compat v1.4.0
  [8f4d0f93] + Conda v1.1.1
  [7073ff75] + IJulia v1.14.1
  [682c06a0] + JSON v0.19.0
  [739be429] + MbedTLS v0.6.6
  [b85f4697] + SoftGlobalScope v1.0.7
  [81def892] + VersionParsing v1.1.3
  [c2297ded] + ZMQ v1.0.0
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [7b1f6079] + FileWatching
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode

(v1.0) pkg> test IJulia
   Testing IJulia
    Status `C:\Users\Klaus\AppData\Local\Temp\jl_4899.tmp\Manifest.toml`
  [b99e7846] BinaryProvider v0.5.2
  [34da2185] Compat v1.4.0
  [8f4d0f93] Conda v1.1.1
  [7073ff75] IJulia v1.14.1
  [682c06a0] JSON v0.19.0
  [739be429] MbedTLS v0.6.6
  [b85f4697] SoftGlobalScope v1.0.7
  [81def892] VersionParsing v1.1.3
  [c2297ded] ZMQ v1.0.0
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [7b1f6079] FileWatching  [`@stdlib/FileWatching`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
comm.jl
ERROR: LoadError: IJulia not properly installed. Please run Pkg.build("IJulia")
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at none:0
 [3] include at .\boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1044
 [5] include(::Module, ::String) at .\sysimg.jl:29
 [6] top-level scope at none:2
 [7] eval at .\boot.jl:319 [inlined]
 [8] eval(::Expr) at .\client.jl:393
 [9] top-level scope at .\none:3
in expression starting at C:\Users\Klaus\.julia\packages\IJulia\DL02A\src\IJulia.jl:45
ERROR: LoadError: LoadError: Failed to precompile IJulia [7073ff75-c697-5162-941a-fcdaad2a7d2a] to C:\Users\Klaus\.julia\compiled\v1.0\IJulia\nfu7T.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] macro expansion at .\logging.jl:311 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1190
 [4] macro expansion at .\logging.jl:309 [inlined]
 [5] _require(::Base.PkgId) at .\loading.jl:947
 [6] require(::Base.PkgId) at .\loading.jl:858
 [7] macro expansion at .\logging.jl:309 [inlined]
 [8] require(::Module, ::Symbol) at .\loading.jl:840
 [9] include at .\boot.jl:317 [inlined]
 [10] include_relative(::Module, ::String) at .\loading.jl:1044
 [11] include(::Module, ::String) at .\sysimg.jl:29
 [12] include(::String) at .\client.jl:392
 [13] top-level scope at C:\Users\Klaus\.julia\packages\IJulia\DL02A\test\runtests.jl:3 [inlined]
 [14] top-level scope at .\none:0
 [15] include at .\boot.jl:317 [inlined]
 [16] include_relative(::Module, ::String) at .\loading.jl:1044
 [17] include(::Module, ::String) at .\sysimg.jl:29
 [18] include(::String) at .\client.jl:392
 [19] top-level scope at none:0
in expression starting at C:\Users\Klaus\.julia\packages\IJulia\DL02A\test\comm.jl:2
in expression starting at C:\Users\Klaus\.julia\packages\IJulia\DL02A\test\runtests.jl:1
ERROR: Package IJulia errored during testing

(v1.0) pkg> status
    Status `C:\Users\Klaus\.julia\environments\v1.0\Project.toml`
  [7073ff75] IJulia v1.14.1

(v1.0) pkg> build IJulia
  Building Conda ──→ `C:\Users\Klaus\.julia\packages\Conda\uQitS\deps\build.log`
  Building ZMQ ────→ `C:\Users\Klaus\.julia\packages\ZMQ\ABGOx\deps\build.log`
  Building MbedTLS → `C:\Users\Klaus\.julia\packages\MbedTLS\r1Ufc\deps\build.log`
  Building IJulia ─→ `C:\Users\Klaus\.julia\packages\IJulia\DL02A\deps\build.log`
┌ Error: Error building `IJulia`:
│ Solving environment: ...working... done
│
│ # All requested packages already installed.
│
│ Error executing Jupyter command 'kernelspec': [Errno 'jupyter-kernelspec' not found] 2
│ [InstallKernelSpec] Removing existing kernelspec in C:\Users\Klaus\AppData\Roaming\jupyter\kernels\julia-1.0
│ [WinError 5] Zugriff verweigert: 'C:\\Users\\Klaus\\AppData\\Roaming\\jupyter\\kernels\\julia-1.0\\logo-32x32.png'
│ [ Info: Installing Jupyter via the Conda package.
│ [ Info: Running `conda install -y jupyter` in root environment
│ [ Info: Found Jupyter version 4.4.0: C:\Users\Klaus\.julia\conda\3\Scripts\jupyter
│ [ Info: Installing Julia kernelspec julia-1.0
│ ERROR: LoadError: failed process: Process(`'C:\Users\Klaus\.julia\conda\3\python.exe' 'C:\Users\Klaus\.julia\conda\3\Scripts\jupyter-kernelspec-script.py' install --replace --user 'C:\Users\Klaus\AppData\Local\Temp\julia-1.0'`, ProcessExited(1)) [1]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
│  [2] pipeline_error at .\process.jl:705 [inlined]
│  [3] #run#504(::Bool, ::Function, ::Cmd) at .\process.jl:663
│  [4] run at .\process.jl:661 [inlined]
│  [5] #installkernel#4(::String, ::Function, ::String) at C:\Users\Klaus\.julia\packages\IJulia\DL02A\deps\kspec.jl:85
│  [6] installkernel(::String) at C:\Users\Klaus\.julia\packages\IJulia\DL02A\deps\kspec.jl:36
│  [7] top-level scope at logging.jl:308
│  [8] top-level scope at logging.jl:307
│  [9] top-level scope at C:\Users\Klaus\.julia\packages\IJulia\DL02A\deps\build.jl:41
│  [10] include at .\boot.jl:317 [inlined]
│  [11] include_relative(::Module, ::String) at .\loading.jl:1044
│  [12] include(::Module, ::String) at .\sysimg.jl:29
│  [13] include(::String) at .\client.jl:392
│  [14] top-level scope at none:0
│ in expression starting at C:\Users\Klaus\.julia\packages\IJulia\DL02A\deps\build.jl:9
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1097

(v1.0) pkg>
'''

**Comment by tokupooh** [comment] 2018-11-24 04:07
@xiaodaigh   @strickek 
I had same problem and detect the cause. See #778. 

To solve this problem, please try the following procedure. 
1. Acess `\AppData\Roaming\jupyter\kernels\julia-1.0`  
2. Remove `logo-32x32.png`, `logo-64x64.png`. 
3. Build `IJulia`

**Comment by strickek** [comment] 2018-11-25 23:04
@tokupooh 
Thank you! Procedure 1 - 3 fixed the problem.

**Comment by JianghuiDu** [comment] 2018-12-20 06:45
It worked, but it makes no sense how this can happen...

**Comment by stevengj** [comment] 2019-01-02 22:14
Is `jupyter kernelspec` changing the permissions?  If not, what is removing write permissions on this directory?

**Comment by stevengj** [comment] 2019-03-27 12:34
We no longer use `jupyter kernelspec` during build, so hopefully this issue is moot.

**Closed by stevengj** 2019-03-27 12:34 UTC
