### ISSUE TITLE
IJulia doesn't play nicely over ipc

### ISSUE THREAD

**Issue by JMurph2015** [JuliaLang/IJulia.jl#561] opened 2017-06-27 06:07 UTC
Hi!
I've been hacking on a variant of the reference jupyter_client, and it seems that IJulia doesn't connect correctly to the ZMQ sockets when the MultiKernelManager is set to 'ipc' mode instead of TCP.  Any thoughts are appreciated, and it's not really critical, I just thought someone should know.

Julia version: 0.5.2
Jupyter Protocol 5.0

**Comment by stevengj** [comment] 2017-06-28 16:38
IJulia [binds ZMQ sockets](https://github.com/JuliaLang/IJulia.jl/blob/master/src/init.jl#L77-L81) with the form `bind(publish[], "$(profile["transport"])://$(profile["ip"]):$(profile["iopub_port"])")` ... is this not correct for ipc?

**Comment by JMurph2015** [comment] 2017-06-28 17:55
That looks about right, but I couldn't really say definitively because I'm not super comfortable with the connection mechanics (pretty good on how the machinery works after a connection is established however).  I'm not sure what's going on, but my client's sockets are all initialized, so it would cause me to think that zmq is trying to bind to IJulia but not finding anything.  I'll also be testing a reference client later today so I'll let you know the results of that.  Here's the the traceback post my code.
```
File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 453, in run_sync
    self.start()
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 863, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 122, in poll
    z_events = self._poller.poll(1000*timeout)
  File "/usr/local/lib/python3.6/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2186)
  File "zmq/backend/cython/_poll.pyx", line 116, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2036)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:2811)
zmq.error.ZMQError: Socket operation on non-socket
```
Thanks!

**Comment by stevengj** [comment] 2017-06-28 17:59
`Socket operation on non-socket` looks like an error on the Python side, not in Julia?

**Comment by JMurph2015** [comment] 2017-06-28 18:03
Yep, but it woks great with any kernels using a IPython or wrapper thereof, just not IJulia, which was why I thought it might be more of a Julia problem.

**Comment by JMurph2015** [comment] 2017-06-28 18:04
ie if IJulia doesn't initialize the sockets at the right time or the right port then the Python client will try to bind, but fail?

**Comment by stevengj** [comment] 2019-03-27 13:10
Closing unless this issue can be reproduced with modern versions.

**Closed by stevengj** 2019-03-27 13:10 UTC
