### ISSUE TITLE
Unknown function in exception access violation

### ISSUE THREAD

**Issue by juliayyan** [JuliaLang/IJulia.jl#433] opened 2016-06-23 21:43 UTC
(possibly a dup of #273)

I am using julia v0.4.5, jupyter notebook version 4.1.0.  My jupyter notebook works fine with python, but I'm seeing the following error message at the commandline when I try running a julia kernel.

```
$ jupyter notebook
[I 22:30:19.200 NotebookApp] Serving notebooks from local directory: C:\cygwin64\home\Julia
[I 22:30:19.200 NotebookApp] 0 active kernels
[I 22:30:19.200 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 22:30:19.200 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 22:30:28.311 NotebookApp] Creating new notebook in
[I 22:30:29.805 NotebookApp] Kernel started: 4e0a34d5-855f-4b14-969b-5a611810f859

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x0 -- unknown function (ip: 0000000000000000)
unknown function (ip: 0000000000000000)

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6978c644 -- unknown function (ip: 000000006978C644)
unknown function (ip: 000000006978C644)
unknown function (ip: 0000000069785939)
zmq_ctx_term at C:\cygwin64\home\Julia\.julia\v0.4\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libzmq.DLL (unknown line)
close at C:\cygwin64\home\Julia\.julia\v0.4\ZMQ\src\ZMQ.jl:158
jlcall_close_1397 at  (unknown line)
jl_apply_generic at C:\Users\Julia\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_svec_fill at C:\Users\Julia\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_gc_inhibit_finalizers at C:\Users\Julia\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_load_and_lookup at C:\Users\Julia\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_compile at C:\Users\Julia\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_trampoline at C:\Users\Julia\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_svec_fill at C:\Users\Julia\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_gc_run_all_finalizers at C:\Users\Julia\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_atexit_hook at C:\Users\Julia\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_exit at C:\Users\Julia\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
jl_throw_in_ctx at C:\Users\Julia\AppData\Local\Julia-0.4.5\bin\libjulia.dll (unknown line)
_chkstk at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
RtlImageNtHeaderEx at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
KiUserExceptionDispatcher at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
[W 22:30:39.892 NotebookApp] Timeout waiting for kernel_info reply from 4e0a34d5-855f-4b14-969b-5a611810f859
[I 22:30:41.802 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 4e0a34d5-855f-4b14-969b-5a611810f859 restarted
```

Any help is appreciated.  Thanks!

**Comment by stevengj** [comment] 2017-01-18 21:16
Could this be a duplicate of #489?  Try the workaround suggested there.

**Comment by stevengj** [comment] 2019-03-27 13:37
Closing as no longer reproducible.

**Closed by stevengj** 2019-03-27 13:37 UTC
