### ISSUE TITLE
Receive the message "The kernel appears to have died" when running

### ISSUE THREAD

**Issue by weijianzhang** [JuliaLang/IJulia.jl#273] opened 2015-02-14 20:40 UTC
I am using Julia v 0.3.5 with IPython notebook 2.1.0. My IPython notebook works fine with Python.  
But when I run `ipython notebook --profile julia`. I constantly receive the message "The kernel appears to have died. It will restart automatically". 

Could you let me know how I can resolve this issue?

Thanks,

Weijian

**Comment by jiahao** [comment] 2015-02-14 21:48
Essentially a newer report of #159

Which Python are you using? Is it from Anaconda?

Your IPython version is a little old, try upgrading it.

**Comment by weijianzhang** [comment] 2015-02-14 23:16
Thanks for the quick reply. 

> Which Python are you using? Is it from Anaconda?
I am using Python 2.7.9 :: Anaconda 2.0.0 (64-bit).

I just upgraded my IPython to 2.4.1 and tried `Pkg.rm("IJulia")`, then `Pkg.add(IJulia)`. But 
I still got the same error.

**Comment by stevengj** [comment] 2015-02-17 21:24
See the [debugging info](https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems) I just added to the README for instructions on how to get a more informative error message.

**Comment by lstagner** [comment] 2015-06-10 11:16
I have been running into this problem when using PyPlot.jl It has made using the Julia notebook almost impossible. I captured the segfault

https://gist.github.com/lstagner/079aaf73acfd386389c3#file-crash-txt-L154

I noticed that the segfaults are preceded by repeated PyCall errors (Interestingly the PyCall errors only occur when running in the notebook). 

Heres my version info
```julia
julia> versioninfo()
Julia Version 0.3.9
Commit 31efe69 (2015-05-30 11:24 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by lstagner** [comment] 2015-06-10 23:26
This snippet reproduces the segfault
```julia
using PyPlot
for i=1:5
    x = rand(50,50)
    fig,ax = plt.subplots()
    p = ax[:pcolor](x)
    cb = fig[:colorbar](p)
    plt.close("all")
end
```

**Comment by lstagner** [comment] 2015-06-12 06:49
Just for fun I ran the above snippet in the notebook on Julia master and I get a new segfault. 

https://gist.github.com/lstagner/17c8aef9d39458eb6870

Does anyone know what is going wrong? I was going to include my notebooks in a paper I'm writing but if this bug persists I wont be able to do that.

**Comment by Carreau** [comment] 2015-06-12 14:49
That might be because the internal structure of Python changed, and [PyCall](https://github.com/stevengj/PyCall.jl) which is used by PyPlot does not work with it (yet).

**Comment by stevengj** [comment] 2015-06-12 17:53
@Carreau, what changes are you referring to?  I use PyPlot with Python 2.7.9 with no problems.

@lstagner, what does `PyPlot.version` (which gives your matplotlib version) return?

**Comment by yuyichao** [comment] 2015-06-12 17:55
@stevengj I just tried it and got the crash.

I'm on `python 3.4.3` (IIRC @lstagner has `3.4.1` in his output) and yesterday's master for `PyCall`, `IJulia` and `julia`

**Comment by stevengj** [comment] 2015-06-12 17:56
There have been some problems with Python 3 and array passing recently; I'm hoping that these will go away once we replace the current numpy-based stuff with a new implementation with @jakebolewski based on the Python buffer interface.

**Comment by jakebolewski** [comment] 2015-06-12 18:01
@lstagner thanks for the reduced test case.  Providing small examples that fail will help out a lot when implementing and testing the buffer protocol change.

**Comment by Carreau** [comment] 2015-06-12 18:38
> @Carreau, what changes are you referring to? I use PyPlot with Python 2.7.9 with no problems.

I was refering to the fact that @lstagner traceback was on Python 3.  CPython got some changes recently (I don't remember which version though) where they finally unified some things at Ast level and it breaks  a few tings like, unittests, and compat with some packages in werid places where you wouldn't expect that to actually break .

**Comment by lstagner** [comment] 2015-06-12 19:25
@stevengj here is the version info
```julia
julia> versioninfo()
Julia Version 0.4.0-dev+5339
Commit 190afa6* (2015-06-12 05:01 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> PyPlot.version
v"1.4.3"

julia> matplotlib[:__version__]
"1.4.3"

shell> python --version
Python 3.4.3 :: Anaconda 2.2.0 (64-bit)
```

IIRC I had a similar problem using python 2. I will switch back and see if the segfault still occurs

**Comment by lstagner** [comment] 2015-06-12 20:08
I installed a python 2 environment doing the following
```
conda create -n python2 python=2.7 anaconda
source activate python2
```

Running the test case in this environment doesn't produce a session killing segfault but it still fails after creating two of the plots.

![screenshot from 2015-06-12 13 03 47](https://cloud.githubusercontent.com/assets/4305891/8138904/09bb3fdc-1104-11e5-98ef-edb630fd7fdf.png)

**Comment by jessie831024** [comment] 2017-01-17 22:43
When I run Bayesian inference using pymc3 on python3.6 Jupiter, it causes python to quit unexpectedly and kernel restarting: "The kernel appears to have died. It will restart automatically.  Is this a problem with Mac OS Sierra, python3, Jupyter or pymc3?

**Comment by stevengj** [comment] 2017-01-18 00:48
@jessie831024, it sounds like you are not even using Julia, so probably you should look elsewhere.

**Comment by stevengj** [comment] 2019-03-27 13:47
Closing as the original issue is not reproducible.   If someone currently gets a "kernel died" message, it probably has a different cause and should be reported in a new issue.

**Closed by stevengj** 2019-03-27 13:47 UTC
