### ISSUE TITLE
Possible memory leak with IJulia `display`

### ISSUE THREAD

**Issue by hycakir** [JuliaLang/IJulia.jl#828] opened 2019-03-26 15:29 UTC
I am using Julia 1.1 in IJulia v1.18.0. I guess assignments to global variables somehow create a memory leak in IJulia but not in REPL. `GC.gc()` does not return unused memory.
```julia
# Cell 1
function bar()
    return rand(1000,1000,30)
end

# Cell 2
# running this cell several times without `;` at the end causes new allocations
# but no deallocations, memory usage will grow until `OutOfMemoryError()`
arr = bar() 

# Cell 3
arr = nothing
GC.gc() # will not return unused memory
```
I assume this is somehow related to IJulia's `display`. If I use `arr = bar();` with `;` at the end instead, the leak does not occur.

**Comment by mbauman** [comment] 2019-03-26 15:40
All outputs are being stored in the `Out` dictionary — E.g., you can access them all through `Out[2]`, etc.  If you remove all these stored outputs with `empty!(Out)`, then Julia will be able to automatically GC them.

**Comment by stevengj** [comment] 2019-03-26 21:26
Duplicate of #785.    The behavior here is identical to IPython.

**Closed by stevengj** 2019-03-26 21:26 UTC
