### ISSUE TITLE
References to output value of cells kept indefinitely

### ISSUE THREAD

**Issue by cmcaine** [JuliaLang/IJulia.jl#851] opened 2019-07-01 14:06 UTC
Reproduce by repeatedly executing a cell containing:

```julia
GC.gc(); big_array = ones(200000 * 1024);
```

Each time I execute a cell containing that line the resident memory of julia increases by ~1.6G because the garbage collector does not de-allocate previous values of `big_array`.

Executing the same code repeatedly on the julia repl gives the expected result with the GC keeping memory use in check.

This bug makes IJulia a massive memory hog for me.

Software versions:

```
in colin
› jupyter --version
jupyter core     : 4.5.0
jupyter-notebook : 5.7.8
qtconsole        : not installed
ipython          : 7.5.0
ipykernel        : 5.1.1
jupyter client   : 5.2.4
jupyter lab      : 1.0.0
nbconvert        : 5.5.0.dev0
ipywidgets       : 7.4.2
nbformat         : 4.4.0
traitlets        : 4.3.2

in colin
› julia --version  
julia version 1.1.1

in colin
› julia          
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.1 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.1) pkg> status IJulia
    Status `~/.julia/environments/v1.1/Project.toml`
  [7073ff75] IJulia v1.18.1
  [682c06a0] JSON v0.20.0
```

**Comment by mbauman** [comment] 2019-07-03 16:46
Duplicate of #785. It's annoying, I agree, but it's just how most Jupyter kernels (in general) work.

**Closed by mbauman** 2019-07-03 16:46 UTC

**Comment by travigd** [comment] 2019-07-09 23:23
Can this be configurable? Maybe an environment variable (preferable such that this behavior is _off_ by default) that allows you to toggle this? Or a `SAVE_LAST` type thing so that at least memory would plateau instead of just grow forever?

**Comment by cmcaine** [comment] 2019-07-10 11:48
I would like that. I never use `In[]` or `Out[]` and I don't know anyone else who does either :/
