### ISSUE TITLE
Not working in jupyter. 

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaLang/IJulia.jl#705] opened 2018-08-12 17:18 UTC
IJulia is installed and builds correctly. Buy in jupyter it nevers runs

**Comment by bkamins** [comment] 2018-08-13 10:45
I have the same problem on Win10 and Julia 1.0. All installs smoothly and configuration seems correct.

In difference from Julia 0.6.4 when starting a kernel Jupyter prints:

> `NotebookApp] Adapting to protocol v5.0 for kernel`

(which is not printed in Julia 0.6.4)

and then hangs, i.e. evaluating cells in Jupyter Notebook dos not work.

**Comment by stevengj** [comment] 2018-08-16 03:42
Duplicate of #693, probably.

**Closed by stevengj** 2018-08-16 03:42 UTC

**Comment by Bob-McCrory** [comment] 2018-08-20 22:08
I don't think it's exactly the same as #693. I used the "dev IJulia" trick from #693 in the package manager, and individual cells are now evaluating. However, when I try Cell | Run All it hangs partway through a notebook. I'm just learning, so I'm not doing anything sophisticated.
