### ISSUE TITLE
Typing characters '.0' causes cell to freeze

### ISSUE THREAD

**Issue by ManojGopalkrishnan** [JuliaLang/IJulia.jl#924] opened 2020-05-15 13:13 UTC
I am using Julia in a Jupyter notebook in a Chrome browser on Windows 10. Whenever I type a dot followed by the number 0, my cell freezes. So for example I try to give a parameter

x ~ Bernoulli(.01)

Everything is fine till I get to Bernoulli(.

But as soon as I type the 0 character, the cell freezes and starts acting weird. I can't add any more input to that cell. I can't select anything. I can't delete anything. Sometimes the same line number starts to display multiple times, without incrementing the line number.

This is happening reproducibly, I checked with the Julia/ Turing community, and they don't think it is from their end. I'm hoping it's either a known issue with Jupyter notebook, or maybe something with IJulia?

This is not happening when I run Python in the notebook. So seems to be somehow IJulia or Julia-related.

If I type a 0 following a 0 or following a dot, without any preceding characters, this is triggered. If I type 2.0000 or 200000000 and so on, there is no problem.

https://stackoverflow.com/questions/61816652/jupyter-notebook-typing-characters-0-causes-cell-to-freeze?noredirect=1#comment109341218_61816652

**Comment by bkamins** [comment] 2020-05-15 13:43
I can confirm that just writing `(.0)` in an empty cell makes Jupyter stop printing the characters that are consecutively typed (but).

Tested on Ubuntu 0.20.4 LTS + Firefox + Julia 1.4.1 + IJulia 1.21.2

**Comment by stevengj** [comment] 2020-05-15 16:11
Duplicate of codemirror/CodeMirror#6064?

This is a CodeMirror bug (CodeMirror is what does editing in Jupyter notebooks), so if it isn't fixed in CodeMirror master you should report a bug there.  See also #907, #887, #917.

**Closed by stevengj** 2020-05-15 16:11 UTC

**Comment by crstnbr** [comment] 2020-05-20 17:19
FYI, I opened an issue here: https://github.com/codemirror/CodeMirror/issues/6288

**Comment by stevengj** [comment] 2020-07-24 16:18
Since this has been fixed in the latest codemirror update, and hence will be fixed in the next Jupyter release, eventually it will be fixed for everyone.

In the meantime, a workaround is to update your codemirror installation as described [here](https://github.com/JuliaLang/IJulia.jl/issues/887#issuecomment-663610660).
