### ISSUE TITLE
IJulia hangs in println()

### ISSUE THREAD

**Issue by rened** [JuliaLang/IJulia.jl#266] opened 2015-01-27 16:21 UTC
The following snippet works just fine in the REPL, but simply hangs in IJulia. CPU load related to this is zero, so it just seems to wait for something:
```jl
a = {rand(32,32,30)};
println("$(minimum(a))")
```
Running IJulia 0.1.16 on Julia 0.3.5 with IPython version 2.2.0, OSX 10.9.5 in Firefox 35.0.1:

```
1 required packages:
 - IJulia                        0.1.16           
9 additional packages:
 - BinDeps                       0.3.7            
 - Compat                        0.2.10           
 - Homebrew                      0.1.13           
 - JSON                          0.4.0            
 - Nettle                        0.1.7            
 - REPLCompletions               0.0.3            
 - SHA                           0.0.3            
 - URIParser                     0.0.3            
 - ZMQ                           0.1.15           
```

**Comment by stevengj** [comment] 2015-01-28 02:19
The problem is simply that the output is too big: `minimum(a)` is a `32x32x30 Array{Float64,3}`, and `println` is sending the whole thing to the front-end.   Since this is over 200kB of output, you're running into #243.   As explained in JuliaLang/julia#8789 the issue here is an OS-kernel limit on buffer sizes, not a Julia thing per se.

It's not clear if there is much we can do here with single-threaded I/O.  cc: @Keno, @vtjnash

**Comment by stevengj** [comment] 2016-02-11 13:55
Closing as a dup.

**Closed by stevengj** 2016-02-11 13:55 UTC
