### ISSUE TITLE
IJulia and Julia 0.7.0-DEV

### ISSUE THREAD

**Issue by jheinen** [JuliaLang/IJulia.jl#648] opened 2018-04-12 09:38 UTC
I can't install `IJulia` in the current development version (0.7.0-DEV.4858):

```julia
│ # Build failed for IJulia
│   exception =
│    LoadError: UndefVarError: JULIA_HOME not defined
```

Is there any workaround?

**Comment by stevengj** [comment] 2018-04-16 18:41
See #623.  Waiting for work on ZMQ.

**Comment by stevengj** [comment] 2018-04-16 18:41
Duplicate of #637

**Closed by stevengj** 2018-04-16 18:41 UTC
