### ISSUE TITLE
Julia 1.0 kernel never works/responds on Windows jupyter lab session

### ISSUE THREAD

**Issue by onebitbrain** [JuliaLang/IJulia.jl#702] opened 2018-08-10 19:54 UTC
This is probably related to issue #693 since 1.0 and 0.7 are essentially the same, but 1.0 doesn't work either.
![julia](https://user-images.githubusercontent.com/4357912/43978437-7dcc03fa-9ca4-11e8-829f-a08a5e886050.PNG)
During the session I opened a python 3.6 kernel first to make sure it worked, it did.  You can see it uses protocol v5.1.  The Julia kernel uses v5.0 and never works.

**Comment by c123w** [comment] 2018-08-12 09:37
I've had the exact same problem; the Python 3.5 kernel works fine, but the Julia 1.0.0 kernel does not (kernel opens fine but basic calculations like 1+2 run forever). I get the same
`Adapting to protocol v5.0 for kernel 34c38b7b-8a58-4342-950b-acac5dae45cf`
message in the powershell.

**Comment by c123w** [comment] 2018-08-12 10:27
I've done a bit of experimenting, I managed to get IJulia to work by running this in the Julia REPL:
`(v1.0) pkg> add IJulia
ENV["IJULIA_DEBUG"] = true
(v1.0) pkg> build IJulia`
 followed by
`jupyter console --kernel="julia-1.0"` from powershell (not `jupyter-lab` or `jupyter-notebook` from powershell, or `notebook()` from the Julia REPL).

Doing only either one of these two things gave me the same hanging kernel as before.

**Comment by stevengj** [comment] 2018-08-12 13:03
Duplicate of #693.

**Closed by stevengj** 2018-08-12 13:03 UTC
