### ISSUE TITLE
IOPub data rate exceeded, plotly

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaLang/IJulia.jl#528] opened 2017-04-13 21:20 UTC
A new problem when using plotly backend in IJulia:
```julia
using Plots; plotly()
plot(real(sol[:,1]))
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.
```

So it looks like a default setting has been reduced. Unfortunately I can't see how to change this in Julia. Is there an easy way when launching IJulia from the REPL?

**Comment by stevengj** [comment] 2017-04-13 22:10
Apparently this is a bug in Jupyter 5, is that what you are using?  See ioam/holoviews#1181 for a similar problem and discussion of workarounds.

Apparently, this will be fixed in Jupyter 5.1: jupyter/notebook#2368

**Comment by stevengj** [comment] 2017-04-13 22:15
Until then, we could modify the `notebook()` function to launch with `jupyter notebook --NotebookApp.iopub_data_rate_limit=2147483647` if Jupyter 5 is detected.

**Comment by bradleyashton** [comment] 2017-04-13 23:44
using the version bundled with latest Julia 0.5.1 install (Conda):
```shell
grok:bin abradley$ ./jupyter --version
4.3.0
```

**Comment by stevengj** [comment] 2017-04-14 14:43
The data-rate limit was merged in February 2016: jupyter/notebook#931, so I guess it made it into Jupyter 4.3 as well, and maybe into Jupyter 4.2?  I'm surprised that no one has complained until now.

**Comment by stevengj** [comment] 2017-05-02 22:25
Okay, I've updated the `notebook()` command so that it launches Jupyter with the rate-limit disabled for 4.2 ≤ jupyter < 5.1.

**Closed** 2017-05-02 22:24 UTC

**Comment by juliohm** [comment] 2017-11-05 23:16
Hi @stevengj, I am having the same issue with the GR backend now, can you please confirm the issue is not in IJulia anymore? https://github.com/JuliaPlots/Plots.jl/issues/1223

**Comment by stevengj** [comment] 2017-11-06 14:31
If you launch with `IJulia.notebook()` with Jupyter < 5.1, it passes `--NotebookApp.iopub_data_rate_limit=2147483647`.   If you run `jupyter` from a terminal manually, then you need to pass this yourself.

**Comment by juliohm** [comment] 2017-11-06 17:17
On the spot, thanks @stevengj
