### ISSUE TITLE
Broken tab completion after high Unicode codepoints

### ISSUE THREAD

**Issue by mickk-on-cpp** [JuliaLang/IJulia.jl#541] opened 2017-05-12 22:57 UTC
I'm running Julia on a fresh release-0.5 checkout (`0.5.3-pre+0` as of this writing) and a fresh IJulia from master. All tied together with Jupyter 4.3.0.

For most things tab completions appear to be working fine:

```julia
I like \Pi<Tab>
```

becomes:

```julia
I like Π
```

When something such as `\mbfa` aka U+1D41A Mathematical Bold Small A becomes involved then things work sometimes, e.g. this:

```julia
I want \mbfa<Tab> Π
```

becomes:

```julia
I want 𝐚 Π
```

However completion appears to fail anywhere *after* a literal 𝐚 in a cell, so this fails:

```julia
I want 𝐚<Tab>
```

resulting in the following trace:

```
KERNEL EXCEPTION
BoundsError: attempt to access 11-element Array{UInt8,1} at index [12]

 in next at ./strings/string.jl:92 [inlined]
 in chr2ind(::String, ::Int64) at ./strings/basic.jl:245
 in complete_request(::ZMQ.Socket, ::IJulia.Msg) at /home/ijulia/.julia/IJulia/src/handlers.jl:26
 in eventloop(::ZMQ.Socket) at /home/ijulia/.julia/IJulia/src/eventloop.jl:8
 in (::IJulia.##13#19)() at ./task.jl:360
```

**Comment by stevengj** [comment] 2017-05-16 03:24
I can reproduce the problem.  I set `IJulia.set_verbose(true)` so that I can see the messages, and typed `complete 𝐚` followed by tab, and got an error.  The tab-completion request message received from Jupyter was:
```
23:15:48(write task): RECEIVED IPython Msg [ idents 4907C7DC795E40758D813AB5D269A215 ] {
  parent_header = Dict{String,Any}(),
  header = Dict{String,Any}(Pair{String,Any}("msg_id","8EFCD558FE0E4D31B0AD4AC5658232D8"),Pair{String,Any}("msg_type","complete_request"),Pair{String,Any}("username","username"),Pair{String,Any}("date","2017-05-16T03:15:48.723122Z"),Pair{String,Any}("version","5.0"),Pair{String,Any}("session","4907C7DC795E40758D813AB5D269A215")),
  metadata = Dict{String,Any}(),
  content = Dict{String,Any}(Pair{String,Any}("cursor_pos",11),Pair{String,Any}("code","complete 𝐚"))
}
```
This looks like it may be a bug in Jupyter itself.  The string `"complete 𝐚"` only has 10 characters, but it is sending `cursor_pos=11`.

Furthermore, if I try to tab-complete the string `𝐚𝐚𝐚𝐚`, then it sends:
```
23:19:40(write task): RECEIVED IPython Msg [ idents 4907C7DC795E40758D813AB5D269A215 ] {
  parent_header = Dict{String,Any}(),
  header = Dict{String,Any}(Pair{String,Any}("msg_id","0174E318D7404864808471CD77DBA3BE"),Pair{String,Any}("msg_type","complete_request"),Pair{String,Any}("username","username"),Pair{String,Any}("date","2017-05-16T03:19:40.227322Z"),Pair{String,Any}("version","5.0"),Pair{String,Any}("session","4907C7DC795E40758D813AB5D269A215")),
  metadata = Dict{String,Any}(),
  content = Dict{String,Any}(Pair{String,Any}("cursor_pos",10),Pair{String,Any}("code","𝐚𝐚𝐚𝐚𝐚"))
}
```
Notice that `cursor_pos=10` but the string is of length 5!

It looks like Jupyter may be sending us the cursor position in UTF-16 code-units (where `𝐚` is 2 code units because it is outside the BMP), rather than the cursor position in Unicode characters.   @minrk, can you confirm?

**Comment by stevengj** [comment] 2017-05-16 03:30
The reason I say it is a bug is that the [Jupyter spec](http://jupyter-client.readthedocs.io/en/latest/messaging.html) explicitly states that `cursor_pos` is *The cursor position within 'code' (in unicode characters)*.)

**Comment by minrk** [comment] 2017-05-16 11:36
It's a bug in CodeMirror that appears to apply to a specific range of codepoints. Most unicode characters I have tried are handled correctly.

**Comment by stevengj** [comment] 2017-05-16 14:50
Should be fixed now on master; I changed our Jupyter index computation to use UTF-16 code units.

**Closed** 2017-05-16 14:50 UTC
