### ISSUE TITLE
Documentation of ENV clarification

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/IJulia.jl#518] opened 2017-03-07 20:43 UTC
Hi, 
I run into the following:
```
Pkg.build("IJulia")
INFO: Building Conda
INFO: Building Homebrew
Updated 1 tap (homebrew/core).
==> New Formulae
dmtx-utils
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
INFO: Installing Jupyter via the Conda package.
Your PYTHONPATH points to a site-packages dir for Python 3.x but you are running Python 2.x!
     PYTHONPATH is currently: "/usr/local/lib/python3.6/site-packages/"
     You should `unset PYTHONPATH` to fix this.
```

This confused me a bit, since I thought setting `PYTHON` to `""` is all I need to make sure, that IJulia, PyCall, Conda etc, are using their own python.
Reading the IJulia documentation more carefully indicates I need to set `ENV["JUPYTER"] = ""` to make sure Conda.jl is used.
So how does the `PYTHONPATH` fit in here? What is the best recipe, to have all Julia packages use the mini-conda installed by Conda?7

By the way, `unset PYTHONPATH` doesn't seem to be informative to all readers, so something like 
```
set PYTHONPATH to "" (in Julia: ENV["PYTHONPATH"] = ""; Pkg.build("IJulia")) `
might be clearer!

**Comment by stevengj** [comment] 2017-03-07 22:12
The error message that you are seeing comes from Python, not from Julia.  The problem is that Conda runs its own Python, and is getting confused by the `PYTHONPATH` you have set.

This is really a variant of JuliaPy/Conda.jl#13, and should be fixed in Conda: Conda should unset any stray Python environment variables like PYTHONPATH before running its python code

PyCall's build script might also need to do the same thing.

**Comment by stevengj** [comment] 2017-03-07 22:13
There are a number of environment variables that could confuse Python if they are set inconsistently: https://docs.python.org/2/using/cmdline.html

**Comment by SimonDanisch** [comment] 2017-03-10 10:50
Thanks, so there is a fix on the way to simplify this and make it less irritable by the outside world!

**Comment by stevengj** [comment] 2017-03-10 18:05
There is?  I don't see a Conda PR yet.

**Comment by stevengj** [comment] 2019-03-27 13:34
IJulia no longer uses Conda to install.

**Closed by stevengj** 2019-03-27 13:34 UTC
