### ISSUE TITLE
Can't Use on OSX

### ISSUE THREAD

**Issue by arnavs** [JuliaLang/IJulia.jl#967] opened 2020-12-05 21:19 UTC
I am on Julia 1.5.2 and macOS Big Sur. Full version information below. 

```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_CUDA_SILENT = true
```

My Jupyter installation is through Conda (and `which jupyter` returns the right path). This is from a fresh Julia install with only 2 packages. 

Unfortunately, I can't use `IJulia`. It doesn't show any issues when installing or precompiling, but when I open a jupyter notebook (regardless of the contents of the directory, i.e. whether or not any TOML is present), I get this cascade of errors about the `Mbed_TLS` package.

And when I try to start a notebook through the REPL, it asks me to install Jupyter through Miniconda (in `~/.julia/conda`), and crashes if I say no. 

Any advice would be appreciated, especially for the command line startup through Conda.  

```
[ Info: Precompiling IJulia [7073ff75-c697-5162-941a-fcdaad2a7d2a]
ERROR: LoadError: ArgumentError: Package MbedTLS_jll does not have JLLWrappers in its dependencies:
- If you have MbedTLS_jll checked out for development and have
  added JLLWrappers as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with MbedTLS_jll
Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:906
 [2] include(::Function, ::Module, ::String) at ./Base.jl:380
 [3] include(::Module, ::String) at ./Base.jl:368
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:331 [inlined]
 [6] eval(::Expr) at ./client.jl:467
 [7] top-level scope at ./none:3
in expression starting at /Users/arnavsood/.julia/packages/MbedTLS_jll/qMb7d/src/MbedTLS_jll.jl:5
ERROR: LoadError: Failed to precompile MbedTLS_jll [c8ffd9c3-330d-5841-b78e-0817d7145fa1] to /Users/arnavsood/.julia/compiled/v1.5/MbedTLS_jll/u5NEn_M29Nq.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
 [6] include(::Function, ::Module, ::String) at ./Base.jl:380
 [7] include(::Module, ::String) at ./Base.jl:368
 [8] top-level scope at none:2
 [9] eval at ./boot.jl:331 [inlined]
 [10] eval(::Expr) at ./client.jl:467
 [11] top-level scope at ./none:3
in expression starting at /Users/arnavsood/.julia/packages/MbedTLS/4YY6E/src/MbedTLS.jl:3
ERROR: LoadError: LoadError: Failed to precompile MbedTLS [739be429-bea8-5141-9913-cc70e7f3736d] to /Users/arnavsood/.julia/compiled/v1.5/MbedTLS/bf9T0_M29Nq.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
 [6] include(::Function, ::Module, ::String) at ./Base.jl:380
 [7] include at ./Base.jl:368 [inlined]
 [8] include(::String) at /Users/arnavsood/.julia/packages/IJulia/IDNmS/src/IJulia.jl:33
 [9] top-level scope at /Users/arnavsood/.julia/packages/IJulia/IDNmS/src/IJulia.jl:309
 [10] include(::Function, ::Module, ::String) at ./Base.jl:380
 [11] include(::Module, ::String) at ./Base.jl:368
 [12] top-level scope at none:2
 [13] eval at ./boot.jl:331 [inlined]
 [14] eval(::Expr) at ./client.jl:467
 [15] top-level scope at ./none:3
in expression starting at /Users/arnavsood/.julia/packages/IJulia/IDNmS/src/hmac.jl:1
in expression starting at /Users/arnavsood/.julia/packages/IJulia/IDNmS/src/IJulia.jl:309
ERROR: LoadError: Failed to precompile IJulia [7073ff75-c697-5162-941a-fcdaad2a7d2a] to /Users/arnavsood/.julia/compiled/v1.5/IJulia/nfu7T_M29Nq.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
 [6] include(::Function, ::Module, ::String) at ./Base.jl:380
 [7] include(::Module, ::String) at ./Base.jl:368
 [8] exec_options(::Base.JLOptions) at ./client.jl:296
 [9] _start() at ./client.jl:506
in expression starting at /Users/arnavsood/.julia/packages/IJulia/IDNmS/src/kernel.jl:1
[I 16:17:42.506 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
[ Info: Precompiling IJulia [7073ff75-c697-5162-941a-fcdaad2a7d2a]
ERROR: LoadError: ArgumentError: Package MbedTLS_jll does not have JLLWrappers in its dependencies:
- If you have MbedTLS_jll checked out for development and have
  added JLLWrappers as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with MbedTLS_jll
Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:906
 [2] include(::Function, ::Module, ::String) at ./Base.jl:380
```

**Comment by stevengj** [comment] 2020-12-09 17:26
Duplicate of JuliaLang/MbedTLS.jl#198

**Closed by stevengj** 2020-12-09 17:26 UTC
