### ISSUE TITLE
No Output in notebook using Julia 0.4.0 

### ISSUE THREAD

**Issue by achen12** [JuliaLang/IJulia.jl#374] opened 2015-10-13 21:08 UTC
Using the latest Julia and build using conda to get ipython and jupyter.

There doesn't seems to be any output from STDOUT or STDERR in the ipython notebook using both firefox and chrome.  However, Python kernel works fine.

Verbose log (trying to execute foo=2):
```shelll
[D 17:01:33.775 NotebookApp] Connecting to: tcp://127.0.0.1:49246
[D 17:01:33.776 NotebookApp] Connecting to: tcp://127.0.0.1:48666
[D 17:01:33.777 NotebookApp] Connecting to: tcp://127.0.0.1:59551
PROFILE = Dict{AbstractString,Any}("key"=>"893253ba-353a-4332-a29c-c28ea4d3cbad","transport"=>"tcp","signature_scheme"=>"hmac-sha256","ip"=>"127.0.0.1","hb_port"=>36811,"control_port"=>52222,"shell_port"=>49246,"stdin_port"=>59551,"iopub_port"=>48666)
SENDING IPython Msg [ idents status ] {
  header = Dict("msg_id"=>"11aa0da9-e28e-4858-bbbf-557bce5a3e3e","msg_type"=>"status","username"=>"jlkernel","version"=>"5.0","session"=>"????"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict("execution_state"=>"starting")
}
Starting kernel event loops.
got msg part 47A5F9130E3F4D5EA2546634BFA52EF1
got msg part <IDS|MSG>
RECEIVED IPython Msg [ idents 47A5F9130E3F4D5EA2546634BFA52EF1 ] {
  header = Dict{AbstractString,Any}("msg_id"=>"10C8C1F0ACCF433882EDB3DE90AD0AC1","msg_type"=>"kernel_info_request","username"=>"username","version"=>"5.0","session"=>"47A5F9130E3F4D5EA2546634BFA52EF1"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict{AbstractString,Any}()
}
SENDING IPython Msg [ idents status ] {
  header = Dict("msg_id"=>"2a9c690d-ec79-4436-9733-defcd55c06cf","msg_type"=>"status","username"=>"jlkernel","version"=>"5.0","session"=>"????"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict("execution_state"=>"busy")
}
SENDING IPython Msg [ idents 47A5F9130E3F4D5EA2546634BFA52EF1 ] {
  header = Dict("msg_id"=>"84be730d-1ee9-4187-a9ff-d5b067c12789","msg_type"=>"kernel_info_reply","username"=>"username","version"=>"5.0","session"=>"47A5F9130E3F4D5EA2546634BFA52EF1"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict{ASCIIString,Any}("help_links"=>[Dict("text"=>"Julia Home Page","url"=>"http://julialang.org/"),Dict("text"=>"Julia Documentation","url"=>"http://docs.julialang.org/"),Dict("text"=>"Julia Packages","url"=>"http://pkg.julialang.org/")],"language_info"=>Dict("file_extension"=>".jl","name"=>"julia","mimetype"=>"application/julia","version"=>"0.4.0"),"implementation"=>"ijulia","banner"=>"Julia: A fresh approach to technical computing.","protocol_version"=>"5.0")
}
SENDING IPython Msg [ idents status ] {
  header = Dict("msg_id"=>"b81fbbab-b275-44c7-ab10-473b69c67cce","msg_type"=>"status","username"=>"jlkernel","version"=>"5.0","session"=>"????"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict("execution_state"=>"idle")
}
got msg part 47A5F9130E3F4D5EA2546634BFA52EF1
got msg part <IDS|MSG>
RECEIVED IPython Msg [ idents 47A5F9130E3F4D5EA2546634BFA52EF1 ] {
  header = Dict{AbstractString,Any}("msg_id"=>"A0FBC341B0704B97AA8FD4A9869757EC","msg_type"=>"execute_request","username"=>"username","version"=>"5.0","session"=>"47A5F9130E3F4D5EA2546634BFA52EF1"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict{AbstractString,Any}("store_history"=>true,"user_expressions"=>Dict{AbstractString,Any}(),"allow_stdin"=>true,"code"=>"foo = 2","silent"=>false,"stop_on_error"=>true)
}
SENDING IPython Msg [ idents status ] {
  header = Dict("msg_id"=>"08051def-75b7-463a-ab50-f7989ca8ef35","msg_type"=>"status","username"=>"jlkernel","version"=>"5.0","session"=>"????"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict("execution_state"=>"busy")
}
EXECUTING foo = 2
SENDING IPython Msg [ idents execute_input ] {
  header = Dict("msg_id"=>"0bdd7d85-59a8-440e-b40c-a9ac5ab7a298","msg_type"=>"execute_input","username"=>"username","version"=>"5.0","session"=>"47A5F9130E3F4D5EA2546634BFA52EF1"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict{ASCIIString,Any}("code"=>"foo = 2","execution_count"=>1)
}
SENDING IPython Msg [ idents execute_result ] {
  header = Dict("msg_id"=>"b2b7ae33-bad8-49d6-bc0c-53136b86b914","msg_type"=>"execute_result","username"=>"username","version"=>"5.0","session"=>"47A5F9130E3F4D5EA2546634BFA52EF1"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict{ASCIIString,Any}("data"=>Dict{ASCIIString,ByteString}("text/plain"=>"2"),"metadata"=>Dict{Any,Any}(),"execution_count"=>1)
}
SENDING IPython Msg [ idents 47A5F9130E3F4D5EA2546634BFA52EF1 ] {
  header = Dict("msg_id"=>"54834a15-f424-4718-899d-877ea19bc0fe","msg_type"=>"execute_reply","username"=>"username","version"=>"5.0","session"=>"47A5F9130E3F4D5EA2546634BFA52EF1"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict{ASCIIString,Any}("status"=>"ok","payload"=>"","user_expressions"=>Dict{Any,Any}(),"execution_count"=>1)
}
SENDING IPython Msg [ idents status ] {
  header = Dict("msg_id"=>"4a6cddfb-c9e9-4818-b54f-0a6553ce7d8d","msg_type"=>"status","username"=>"jlkernel","version"=>"5.0","session"=>"47A5F9130E3F4D5EA2546634BFA52EF1"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict("execution_state"=>"idle")
}
```

**Comment by stevengj** [comment] 2015-10-13 21:24
Works fine for me, e.g. `println("Hello world.")` works in an 0.4.0 notebook for me.  What is `versioninfo(true)`?

**Comment by achen12** [comment] 2015-10-13 21:28
versioninfo(true)

```shelll
julia> versioninfo(true)
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz
  WORD_SIZE: 64
           Ubuntu 15.04
  uname: Linux 3.19.0-28-generic #30-Ubuntu SMP Mon Aug 31 15:52:51 UTC 2015 x86_64 x86_64
Memory: 7.6790924072265625 GB (7140.0390625 MB free)
Uptime: 34.0 sec
Load Avg:  0.13037109375  0.03173828125  0.0107421875
Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz: 
       speed         user         nice          sys         idle          irq
#1  1752 MHz        390 s          0 s        100 s       2804 s          0 s
#2  2500 MHz        258 s          0 s        180 s       2890 s          0 s
#3  2592 MHz        185 s          0 s         92 s       3025 s          0 s
#4  2622 MHz        139 s          0 s        109 s       3105 s          0 s

  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  TERM = xterm
  XDG_SESSION_PATH = /org/freedesktop/DisplayManager/Session0
  XDG_SEAT_PATH = /org/freedesktop/DisplayManager/Seat0
  DEFAULTS_PATH = /usr/share/gconf/i3.default.path
  PATH = /home/ac/anaconda/bin:/home/ac/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
  MANDATORY_PATH = /usr/share/gconf/i3.mandatory.path
  HOME = /home/ac

Package Directory: /home/ac/.julia/v0.4
2 required packages:
 - IJulia                        1.1.7+             master (dirty)
 - Images                        0.4.50
18 additional packages:
 - BinDeps                       0.3.18
 - ColorTypes                    0.1.7
 - ColorVectorSpace              0.0.5
 - Colors                        0.5.4
 - Compat                        0.7.6
 - Conda                         0.1.7
 - Docile                        0.5.19
 - FixedPointNumbers             0.0.12
 - Graphics                      0.1.3
 - JSON                          0.5.0
 - Nettle                        0.2.0
 - Reexport                      0.0.3
 - SHA                           0.1.2
 - SIUnits                       0.0.5
 - TexExtensions                 0.0.2
 - URIParser                     0.1.1
 - ZMQ                           0.3.0
 - Zlib                          0.1.10
```

**Comment by stevengj** [comment] 2015-10-13 22:52
Note that `foo = 2` is not even using `STDOUT`.  And it is sending the correct `execute_result` of `2`.   What IPython/Jupyter version do you have?   When you type `Pkg.build("IJulia")`, what is the output?

**Comment by stevengj** [comment] 2015-10-13 22:53
Note that if you are using Conda to get Jupyter, then you shouldn't run `ipython` from the command line.  You should run `using IJulia; notebook()` from within Julia to make sure you launch the `jupyter` that Julia installed.

**Comment by achen12** [comment] 2015-10-14 18:07
Thanks!  This also doesn't work in the case of "2", or an explicit print line "println(2)".
Yep, I am using Conda for Jupyter and Ipython.  Unfortunately, both approach of starting IJulia from Julia or Ipython doesn't work.
Several attempts has been made:  Purging ~/.julia, Purging Conda, Purging Julia installation.

**Comment by el-uhu** [comment] 2015-10-20 20:28
I had a similar problem after updating Julia to version 0.4.0 and updating from ipython to jupyter on Ubuntu 15.10.
In my case, running `pip install jupyter --upgrade`, followed by `Pkg.build("IJulia")` resolved the issue.

**Comment by stevengj** [comment] 2015-10-21 00:02
@el-uhu, thanks for the tip, but I'm not sure it applies here since Conda should have a very recent version of Jupyter.

**Comment by el-uhu** [comment] 2015-10-21 09:06
@stevengj True, thanks for pointing that out! But in case anyone running Ubuntu has similar problems, it might help nonetheless.

**Comment by achen12** [comment] 2015-10-21 18:57
Thanks for the input, but unfortunately. it didn't work.  I also got the source and recompiled on my end, which also didn't work.

I might grab 0.3 and try IJulia again.  Perhaps some kernel to jupyter binding is off on my computer.

**Comment by gdkrmr** [comment] 2015-10-22 17:50
I have the same issue: kernel is running but I do not get any output on the notebook. 
Julia 0.4.0, IJulia 1.1.7, and Jupyter 1.0.0 installed with pip.

**Comment by gdkrmr** [comment] 2015-10-22 18:03
I just solved it following https://github.com/IRkernel/IRkernel/issues/8

I installed ```pyzmq``` using the ```--no-use-wheel``` option and rebuilt IJulia.

**Comment by achen12** [comment] 2015-10-23 16:00
thanks @gdkrmr!  I thought purging libzmq was tried, but I guess I was wrong.  Yep.  Purging all libzmqs and doing a new install of libzmq3-dev + rebuild all children packages is the way to go.  Thanks all!

**Comment by stevengj** [comment] 2015-10-23 16:12
@achen12, you are still using Conda?  Maybe this is something that could be worked around in the Conda package, or at least reported upstream, if they have a broken pyzmq update?

**Comment by achen12** [comment] 2015-10-23 16:25
@Stevengj,  Conda works well.  So I think what  Happened was I had libzmq installed via apt-get because I wasn't using conda in Juliav0.3.  Upon building IJulia on Julia v0.4, it started conda and got its own libzmq which conflicted with mine.

Here is my steps using posted solution:
sudo apt-get purge libzmq*
sudo apt-get install libzmq3-dev
rm ~/.julia
rm ~/anaconda
julia
> Pkg.build("IJulia")

After which everything worked.  I think I don't even need to install libzmq3 via apt-get anymore with the conda getting libzmq by itself.

**Comment by stevengj** [comment] 2015-10-23 16:28
cc: @Luthaf, it would be nice if the Conda distribution did not get confused by a `libzmq` installed elsewhere on the system.

**Comment by Luthaf** [comment] 2015-10-23 18:13
Should we set the `LD_LIBRARY_PATH` (or equivalent) in some way? The issue is that we can not simply remove all system path from it.

Also, IJulia is starting a separated process for `jupyter`, and I do not know what environment this process will have (it is cloned from the current envirronement?).

**Comment by stevengj** [comment] 2015-10-23 18:59
The problem with setting an environment variable is that it can affect child processes.   e.g. if we set  `LD_LIBRARY_PATH` when we launch `jupyter`, I believe that will be in the environment of the `julia` kernel when it launches.

**Comment by stevengj** [comment] 2015-10-23 19:00
Ideally, Anaconda would hard-code the paths of the shared libraries that it loads, so that it isn't affected by system paths.

**Comment by shashi** [comment] 2015-11-16 04:44
I am running into this issue as well (without Conda)

I tried the steps @achen12 described but got

`ImportError: libzmq.so.1: cannot open shared object file: No such file or directory` during Pkg.build

so had to also install `libzmq1` to make it go away.

This is the output I get with IJulia.set_verbose()

```julia
got msg part F337C92065F244A787A30E8EF2D59F02
got msg part <IDS|MSG>
RECEIVED IPython Msg [ idents F337C92065F244A787A30E8EF2D59F02 ] {
  header = Dict{AbstractString,Any}("msg_id"=>"D8C2C003EEB84628B6CF560C91B8E6D0","msg_type"=>"execute_request","username"=>"username","version"=>"5.0","session"=>"F337C92065F244A787A30E8EF2D59F02"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict{AbstractString,Any}("store_history"=>true,"user_expressions"=>Dict{AbstractString,Any}(),"allow_stdin"=>true,"code"=>"1+1","silent"=>false,"stop_on_error"=>true)
}
SENDING IPython Msg [ idents status ] {
  header = Dict("msg_id"=>"e3a1350d-0af4-4be7-82d1-e00b36e4210c","msg_type"=>"status","username"=>"jlkernel","version"=>"5.0","session"=>"F337C92065F244A787A30E8EF2D59F02"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict("execution_state"=>"busy")
}
EXECUTING 1+1
SENDING IPython Msg [ idents execute_input ] {
  header = Dict("msg_id"=>"82ee9004-5216-430f-886c-f3a1c89c3809","msg_type"=>"execute_input","username"=>"username","version"=>"5.0","session"=>"F337C92065F244A787A30E8EF2D59F02"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict{ASCIIString,Any}("code"=>"1+1","execution_count"=>6)
}
SENDING IPython Msg [ idents execute_result ] {
  header = Dict("msg_id"=>"4ec63378-c0cf-412f-b96a-aa3305b83ba2","msg_type"=>"execute_result","username"=>"username","version"=>"5.0","session"=>"F337C92065F244A787A30E8EF2D59F02"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict{ASCIIString,Any}("data"=>Dict{ASCIIString,ByteString}("text/plain"=>"2"),"metadata"=>Dict{Any,Any}(),"execution_count"=>6)
}
SENDING IPython Msg [ idents F337C92065F244A787A30E8EF2D59F02 ] {
  header = Dict("msg_id"=>"3b2a6913-8dfc-4609-98b7-583e6b9781a9","msg_type"=>"execute_reply","username"=>"username","version"=>"5.0","session"=>"F337C92065F244A787A30E8EF2D59F02"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict{ASCIIString,Any}("status"=>"ok","payload"=>"","user_expressions"=>Dict{Any,Any}(),"execution_count"=>6)
}
SENDING IPython Msg [ idents status ] {
  header = Dict("msg_id"=>"867827dd-2eea-4e48-809d-6c4c3c70e127","msg_type"=>"status","username"=>"jlkernel","version"=>"5.0","session"=>"F337C92065F244A787A30E8EF2D59F02"),
  metadata = Dict{AbstractString,Any}(),
  content = Dict("execution_state"=>"idle")
}
```

And the web socket messages are:

From browser
```
{"header":{"msg_id":"D8C2C003EEB84628B6CF560C91B8E6D0","username":"username","session":"F337C92065F244A787A30E8EF2D59F02","msg_type":"execute_request","version":"5.0"},"metadata":{},"content":{"code":"1+1","silent":false,"store_history":true,"user_expressions":{},"allow_stdin":true,"stop_on_error":true},"buffers":[],"parent_header":{},"channel":"shell"}
```
to browser
```
{"parent_header": {"username": "username", "msg_type": "execute_request", "msg_id": "D8C2C003EEB84628B6CF560C91B8E6D0", "version": "5.0", "session": "F337C92065F244A787A30E8EF2D59F02"}, "msg_type": "execute_reply", "msg_id": "3b2a6913-8dfc-4609-98b7-583e6b9781a9", "content": {"status": "ok", "execution_count": 6, "payload": "", "user_expressions": {}}, "header": {"username": "username", "msg_type": "execute_reply", "msg_id": "3b2a6913-8dfc-4609-98b7-583e6b9781a9", "version": "5.0", "session": "F337C92065F244A787A30E8EF2D59F02"}, "channel": "shell", "buffers": [], "metadata": {}}
```
So it looks like `execute_result` messages aren't being received by the browser.

I'm on IJulia master and have tried both ZMQ release and master with the same effect.

I'm on Ubuntu 14.04. Other info:

```
julia> versioninfo()
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

```
(jupyterenv)notebooks > jupyter --version
4.0.4
```

**Comment by stevengj** [comment] 2015-11-16 19:16
@shashi, does Jupyter work with the IPython kernel?  If not, it is a Jupyter issue.

**Comment by shashi** [comment] 2015-11-17 08:12
It does work with the Python kernel...

**Comment by stevengj** [comment] 2015-11-17 13:24
@shashi, I'm confused, because `ImportError` is a Python exception, and IJulia itself does not use Python.  That means that the exception is being thrown by `jupyter`.  But that means it should affect communication with any back-end, no?   Did you try the Conda `jupyter` with the IPython kernel?

**Comment by shashi** [comment] 2015-11-17 13:59
Oh the `ImportError` goes away if I install libzmq1 - and then only Python works, but not Julia...

It seems that some communication still happens. For example if I say `sleep(5)` the `In [*]` stays for about 5 seconds.

**Comment by JobJob** [comment] 2015-11-17 18:30
Does `println("aloha")` print the output at least? 

Seems like maybe you're getting all messages from the kernel except the ones with `msg["header"]["msg_type"] == "execute_result"`? 

After executing a cell, what's the sequence of values of the `msg["header"]["msg_type"]` in the browser websocket requests pane (I'm using Chrome and can see them)? (Just in case you didn't think of it, you can parse them at the repl with `msg = JSON.parse("""copy paste msg here""")`). 

The normal sequence is:

1. status (busy)
1. execute input (repeats the code sent back to the client (not sure why exactly))
1. execute_result (returns the result which is normally displayed as Out[1])
1. execute_reply (code executed with "error" or "ok")
1. status (idle)

Actually I notice that the IPython kernel sends the status (idle) before the execute_reply (i.e. 4. and 5. are reversed). I wonder if that could be part of the problem?

I think the [*] goes away when the status(idle) is received, so I'm guessing you are at least receiving that.

**Comment by rdeits** [comment] 2016-02-09 18:05
I believe I had the exact same issue, which I was just able to fix thanks to the hint from @gdkrmr. I'm on Ubuntu 14.04 with Julia 0.4 as well. 

I initially had no output at all from the IJulia kernel, but the Python kernel worked just fine. Purging `libzmq*` and installing `libzmq3-dev` resulted in exactly the same `ImportError` that @shashi has. Fixing that error required that I also uninstall the `pyzmq` package, since it looks like that python package was still looking for the old ZMQ library. 

So, the complete set of steps to resolve the issue for me was:

```
sudo apt-get purge libzmq*
sudo pip uninstall pyzmq
rm -rf ~/.julia
sudo apt-get install libzmq3-dev
sudo pip install pyzmq
julia
julia> Pkg.add("IJulia")
julia> Pkg.build("IJulia") 
```

Note that `Pkg.add("IJulia")` fails due to #13915 but the workaround is just to run `Pkg.build("IJulia")` afterward. 

I now have a fully working IJulia notebook on Ubuntu, for the first time in weeks!

**Comment by shashi** [comment] 2016-02-10 02:12
As it turned out, for me what worked was uninstalling ipython 4 from my
machine and just doing Pkg.add("IJulia")

It installed the conda environment and jupyter without problems.

**Comment by stevengj** [comment] 2016-02-10 03:10
@shashi, you don't have to uninstall ipython to use the Conda jupyter.  Just do:
```jl
ENV["JUPYTER"]=""
Pkg.build("IJulia")
```

**Comment by shashi** [comment] 2016-02-10 09:33
@stevengj Cool! I think this issue can be closed now

**Closed** 2016-02-10 15:13 UTC
