### ISSUE TITLE
Urgent: Julia on Jupyter notebook, error:keep restarting kernel

### ISSUE THREAD

**Issue by Renian-L** [JuliaLang/IJulia.jl#982] opened 2021-02-01 16:58 UTC
I'm running Julia on Jupter notebook, but it always shows "kernel died. It will restart automatically." Here is the screenshot of Julia command.
<img width="568" alt="image" src="https://user-images.githubusercontent.com/78372342/106490897-361eb000-64ae-11eb-9c2e-f93aadc5744a.png">

**Comment by stevengj** [comment] 2021-02-01 17:19
What is Julia `versioninfo()`?

**Comment by stevengj** [comment] 2021-02-01 17:19
See also https://julialang.github.io/IJulia.jl/stable/manual/troubleshooting/#Debugging-IJulia-problems

**Comment by Renian-L** [comment] 2021-02-01 17:21
> What is Julia `versioninfo()`?

Thank you for your response. Here is my results of versioninfor()
<img width="567" alt="image" src="https://user-images.githubusercontent.com/78372342/106494116-ef32b980-64b1-11eb-8b55-903760dbe57d.png">

**Comment by stevengj** [comment] 2021-02-01 17:48
Sounds like a duplicate of #968.

**Closed by stevengj** 2021-02-01 17:48 UTC
