### ISSUE TITLE
IJulia array size limit when looping over 2d array?

### ISSUE THREAD

**Issue by evanmason** [JuliaLang/IJulia.jl#406] opened 2016-02-11 12:36 UTC
Hi, when working in IJulia (v1.1.8, Linux machine) I find that the following code prints the iteration output and then hangs and I have to restart the kernel:
```
mask = zeros(Float64, (80, 15))
for iter in CartesianRange(size(mask))
    @show iter.I[1], iter.I[2], mask[iter.I[1], iter.I[2]]
end
```
If I make the size of `mask` a little smaller (say 80, 10), it works fine.

At the REPL I can use any size for `mask` without any problem.

I'm not sure if this is a bug or a particularity of my environment.  Can this behaviour be replicated?

Thanks, Evan

**Comment by evanmason** [comment] 2016-02-11 13:40
I see the same behaviour on Mac OS El Capitan.

**Comment by stevengj** [comment] 2016-02-11 13:55
Probably a duplicate of #243.

**Closed by stevengj** 2016-02-11 13:55 UTC

**Comment by JobJob** [comment] 2016-02-11 16:57
Think it's more likely a dup of https://github.com/JuliaLang/IJulia.jl/issues/372 

It works for me with the IO changes on master (but not on v1.18), @evanmason does `Pkg.checkout("IJulia")` then restarting the kernel fix it for you?

@stevengj could be an idea to tag a new version?

**Comment by evanmason** [comment] 2016-02-11 17:22
Yes, it now works.  Thanks very much for that, Evan

**Comment by stevengj** [comment] 2016-02-11 18:22
Could be worth tagging a new version.
